### ISSUE TITLE
Readme 파일 업데이트하기

### ISSUE THREAD

**Issue by inureyes** [inureyes/gradios#1]
## 요구사항

 * 현재 Readme 파일에는 별 내용이 없습니다.
 * 간단한 프로젝트에 대한 설명을 추가합시다.

## 할 일

- [x] 프로젝트 설명 추가하기
- [x] 기존 프로젝트 개발자에 대한 크레딧 보존하기

**Comment by inureyes-test** [comment]
I'll do this.
