### ISSUE TITLE
[BUG] 플레이어 기체가 화면 밖으로 벗어나는 버그

### ISSUE THREAD

**Issue by wogns3623** [inureyes/gradios#177]
**Describe the bug**
플레이어의 기체가 화면에 끝에 도달해도 멈추지 않고 화면 밖으로 벗어나서까지 이동이 가능한 버그가 있습니다

**To Reproduce**
1. 화면 밖으로 이동한다

**Expected behavior**
화면 밖으로 이동하려고 하면 막혀서 더이상 이동하지 못함

**Screenshots**
![image](https://user-images.githubusercontent.com/42717042/56187769-a3a1e800-605e-11e9-82cd-d7286654d3f4.png)

**Desktop (please complete the following information):**
 - OS: Window 10
 - Browser CHrome

**Additional context**

**Todo
- [ ] 기체가 화면 밖으로 나가지 않도록 코드 수정하기

**Comment by wogns3623** [comment]
추가적으로 화면 밖에서는 적의 공격에 대해 무적인 버그또한 존재합니다

**Comment by doublik** [comment]
제가 하겠습니다.
