### ISSUE TITLE
[BUG] Chrome에서 실행이 안됨

### ISSUE THREAD

**Issue by siroch** [inureyes/gradios#183]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
크롬에서 실행시 검은 화면만 뜨고 아무런 행위를 할 수 없음

**어떤 해결책을 선호하는지 설명해주세요**
크롬에서 작동하게 해주세요

**고려했던 대안들에 대해 설명해주세요**

**추가적인 컨텍스트**

**Comment by 3people** [comment]
해결해보겠습니다

**Comment by 3people** [comment]
해결후에도 화면이 정상적으로 출력되지 않는 이슈가 있습니다
크롬에서만 실행되게 만들었습니다

**Comment by siroch** [comment]
문제 발생했습니다.크롬에서 화면에 출력오류가 발생합니다.

**Comment by AnOldStory** [comment]
제가 해결해보겠습니다
