### ISSUE TITLE
[FEATURE]게임 진행시 enemy의 위치분포.

### ISSUE THREAD

**Issue by aeuna** [inureyes/gradios#187]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
게임 진행시  enemy의 분포가 너무 정형화 되어있습니다.

**어떤 해결책을 선호하는지 설명해주세요**
enemy가 게임화면을 벗어나지 않고 적의 위치가 랜덤하게 나왔으면 좋겠습니다.

**추가적인 컨텍스트**
- [x] enemy가 게임화면을 벗어나지 않고 적의 위치가 랜덤하게 등장하기

**Comment by wogns3623** [comment]
이것은 버그가 아니라 게임 본연의 문제인 듯 하여 bug카테고리에 맞지 않습니다. 카테고리를 기능 추가 요청으로 바꿔주세요

**Comment by aeuna** [comment]
넵 알겠습니다

**Comment by doublik** [comment]
제가 해보겠습니다.
