### ISSUE TITLE
[BUG] html 파일을 로컬에서 직접 열 때 실행이 되지 않는 문제

### ISSUE THREAD

**Issue by jdekim43** [inureyes/gradios#196]
**Describe the bug**
file scheme 를 허용하지 않아 웹서버 없이 로컬에서 바로 파일을 열면 게임이 실행되지 않음.

**To Reproduce**
1. Go to 'project folder'
2. Click on 'index.html'
3. See error

**Expected behavior**
게임이 실행된다.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: any
 - Browser: any
 - Version: current

**Smartphone (please complete the following information):**
 - Device: any
 - OS: any
 - Browser: any
 - Version: current

**Additional context**
#183 이슈와 관련있음.

**Comment by wogns3623** [comment]
Internet Explore나 FireFox에서는 실행이 됩니다. 어떤 상황에서 동작하지 않는지 조금 더 명확하게 설명해주세요

**Comment by jdekim43** [comment]
이 이슈는 크롬의 보안 정책으로 인해 발생되는 문제로 file scheme 가 허용되지 않아서 발생합니다.
이 문제를 해결하는 가장 간단한 방법은 로컬 웹서버를 사용해 파일에 접근하는 것입니다.
