### ISSUE TITLE
[FEATURE] 무기 업그레이드

### ISSUE THREAD

**Issue by siroch** [inureyes/gradios#207]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
적을 처치했을때 무기를 업그레이드 시켜주는 아이템이 나오게 해주세요

**어떤 해결책을 선호하는지 설명해주세요**
적 처치시 총알처럼 아이템이 나오고 이동하게 만들기
업그레이드 실행 시 공격력 증가(추후 한방에 죽지 않는 적들을 처리하기 위해 만들기)

**고려했던 대안들에 대해 설명해주세요**

**추가적인 컨텍스트**

- [x] 무기 업그레이드 기능 추가
- [x] 업그레이드시 범위 향상 and 공격력 증가

**Comment by sejin1031** [comment]
공격력이 존재하기 위해서는 추가적으로 적의 체력이 추가가 되어야 할 듯 합니다.
