### ISSUE TITLE
[FEATURE] 비행기 종류 추가하기

### ISSUE THREAD

**Issue by ji-yoon-e** [inureyes/gradios#211]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
비행기 종류 추가하기

**어떤 해결책을 선호하는지 설명해주세요**
모양의 다양성을 줍니다.

**추가적인 컨텍스트**

- [ ] 비행기 종류 추가하기

**Comment by sujeong1217** [comment]
제가 비행기 종류 추가 하겠습니다.
