### ISSUE TITLE
[FEATURE] 배경에 오브젝트 추가

### ISSUE THREAD

**Issue by tutu772** [inureyes/gradios#215]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
지금의 게임 화면은 너무 단조로워 플레이어가 플레이하는데 있어서 다소 심심할 수 있을것 같습니다.

**어떤 해결책을 선호하는지 설명해주세요**
따라서 우주라는 배경에 맞게 우주에 관한 구조물들을 배경에 추가해주길 원합니다.

**고려했던 대안들에 대해 설명해주세요**
.우주 정거장이나, 행성이나 소행성같은 오브젝트들을 추가하면 좋을 것 같습니다.

**추가적인 컨텍스트**

**Comment by mjkya** [comment]
제가 해보겠습니다.

**Comment by mjkya** [comment]
add background #364
로 해결했습니다.
