### ISSUE TITLE
[FEATURE] 난이도 추가 요청

### ISSUE THREAD

**Issue by siroch** [inureyes/gradios#228]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
시작시 난이도를 선택할 수 있게 해주었으면 좋겠습니다. 쉬움 보통 어려움

**어떤 해결책을 선호하는지 설명해주세요**
난이도에 따라서 게임이 변경된다.
1.개체수 조절
2.적이 나타나는 패턴 조정
3.적의 공격속도증가or연발 기능 추가

**Comment by KRCHOIJUNHO** [comment]
게임이 판수가 증가함에 따라 공격하는 빈도수는 이미 증가하고 있으므로 개체수만 하면 어떨까 싶습니다.

**Comment by qaeqwg** [comment]
난이도가 증가함에 따라 적 개체들이 한 줄로 같이 움직이지 않고 독립적으로 움직이면 좋을 거 같습니다

**Comment by a6gongi** [comment]
난이도가 증가한다면 적들이 좀 더 빠른 총을 쏘거나, 연발로 쏜다면 좀 더 어려울것 같습니다.

**Comment by siroch** [comment]
난이도가 높아지는데 어려워지는건 당연한거 아닌가요?

**Comment by siroch** [comment]
수정했습니다
