### ISSUE TITLE
[FEATURE] 플레이어 기체의 히트박스가 명확하지 않습니다

### ISSUE THREAD

**Issue by wogns3623** [inureyes/gradios#229]
## 요구사항
* 플레이어 기체의 히트박스가 직사각형으로 되어있어 안맞는거같은 적의 총알에 맞는 경우가 종종 있습니다.
* 히트박스가 기체의 모형을 따라가긴 힘들겠지만 직사각형의 히트박스인경우 기체 이미지와 비교했을 때 비는 부분이 많습니다.

## 할일
- [ ] 플레이어 기체의 히트박스를 조금 더 정밀하게 수정하기
- [ ] 적 기체의 히트박스도 정밀하게 수정하기

**Comment by doublik** [comment]
제가 해보겠습니다.

**Comment by doublik** [comment]
플레이어 기체의 히트박스 y픽셀을 절반으로 줄인후 히트박스 위치를 재조정하였습니다.
적 기체의 히트박스의 x픽셀을 조정하였습니다.
tween 을 사용하여 적이 앞뒤로 움직이는 과정에서 앞으로갈때의 히트박스는 정상적이지만 뒤로갈때 히트박스가 비정상적으로 앞에 있습니다. tween이 yoyo 를 처리하는 과정에서 발생하는데, 이는 phaser js의 버그같습니다.

**Comment by doublik** [comment]
히트박스를 조정해주는 과정에서 잘못된 라인에 넣어 버그가 발생하여 재수정하였습니다.
