### ISSUE TITLE
[FEATURE] 게임 종료 화면에 Restart, Exit 버튼 추가

### ISSUE THREAD

**Issue by Rory0304** [inureyes/gradios#230]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
게임 종료 버튼과 재시작 버튼이 분리되어 있어서 게임 종료 화면이 부자연스러워 보이는 것 같습니다. 이보다는 게임 종료 화면에 Restart와 Exit 버튼을 추가하는 방법이 괜찮을 것 같습니다.

**어떤 해결책을 선호하는지 설명해주세요**
게임 종료 화면에 Restart버튼과 Exit 버튼을 추가하고 디자인도 게임의 컨셉(우주)에 어울렸으면 좋겠습니다.

**고려했던 대안들에 대해 설명해주세요**
**추가적인 컨텍스트**

**Comment by doublik** [comment]
제가 해결했습니다.
