### ISSUE TITLE
[BUG] 피격시 나오는 폭팔이펙트가 사라지지 않음

### ISSUE THREAD

**Issue by wogns3623** [inureyes/gradios#233]
**Describe the bug**
게임 진행중에 적 기체가 파괴됬을 때 나오는 폭팔이펙트가 play되고 나서 화면에 보이지는 않지만, 사라지지 않아서 게임을 계속 실행할 시 잔여 오브젝트들이 화면에 남게 됩니다.
이는 게임 성능에 직결되는 문제이므로 빠른 해결이 필요할 것 같습니다.

**To Reproduce**
1. 총알에 기체가 피격당함
2. 폭팔이펙트가 나옴
3. See error

**Expected behavior**
폭팔 이펙트가 play되고 난 후에 오브젝트를 삭제하여 잔여 오브젝트가 남지 않게 함

**Screenshots**
![image](https://user-images.githubusercontent.com/42717042/56192768-1369a000-606a-11e9-9779-539b8c53e422.png)
스크린샷은 현재 이미지가 로딩되지 않는 버그에 걸렸을 때 찍은 스크린샷으로, 피격 후 폭팔이펙트를 재생시키는 오브젝트가 사라지지 않고 남아서 후에 게임이 멈춘 상황입니다.

**Additional context**

**Comment by siroch** [comment]
제가 해보겠습니다.
