### ISSUE TITLE
[FEATURE]게임종료시 score 결과화면 추가

### ISSUE THREAD

**Issue by aeuna** [inureyes/gradios#234]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
게임 종료 후에도 현재 score: 점수 로 흰글씨로 창 상단 왼쪽에 나오는데 결과가 눈에 확 드러났으면 좋겠습니다.

**어떤 해결책을 선호하는지 설명해주세요**
게임 종료 후, 다른 장면으로 넘어가거나 결과 창이 따로 가운데에 나타났으면 좋겠습니다.

**Comment by doublik** [comment]
제가 한번 해보겠습니다.
