### ISSUE TITLE
[FEATURE] 게임시작시 메인화면 출력

### ISSUE THREAD

**Issue by cvivis** [inureyes/gradios#236]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
앞으로 비행기 디자인선택 이나 난이도 선택등 게임 시작전 설정할 부분이 늘어날 것이기에 현재의 장면으로는 부족할 것이라고 생각합니다.

**어떤 해결책을 선호하는지 설명해주세요**
다른 여타 게임처럼 메인화면을 만들고 그다음에 게임을 시작하는것으로 해결하는것이 좋겠습니다.

**추가적인 컨텍스트**
난이도조절이나 비행기디자인과 관련된 버튼을 누르고 설정한뒤 게임을 시작하는 방식이 좋겠습니다.

**Comment by doublik** [comment]
제가하겠습니다.

**Comment by doublik** [comment]
이미지 파일들이 없기때문에 임시로 흰색바탕에 게임스타트 버튼만 만들었습니다.
