### ISSUE TITLE
[FEATURE] 랭킹 시스템 추가 요청

### ISSUE THREAD

**Issue by duncan2121** [inureyes/gradios#241]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
게임이 다 끝나고 스코어가 뜨는 화면에서 랭킹 시스템이 있으면 좋겠습니다. ( 1~5위 정도)

**어떤 해결책을 선호하는지 설명해주세요**
게임이 종료되고 나서 닉네임을 입력하고 점수를 비교하여 표시하려는 랭킹까지만 표시하는 창을 만들었으면 좋겠습니다. 

**고려했던 대안들에 대해 설명해주세요**
점수를 다 저장하지 않고, 표시하려는 랭킹까지만 저장해서 비교해서 점수에따라 또 넣고 빼고를 해주면 더 좋지 않을까 생각합니다.

**Comment by mjkya** [comment]
제가 해보겠습니다.

**Comment by pbt98** [comment]
제가 하겠습니다.
