### ISSUE TITLE
[FEATURE] enemy 비행기와 충돌

### ISSUE THREAD

**Issue by minb234** [inureyes/gradios#245]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
플레이어의 비행기가 적 비행기를 통과해서 겹쳐도 이동이 가능합니다.

**어떤 해결책을 선호하는지 설명해주세요**
지금은 적비행기가 발사하는 투사체를 맞을 경우에만 health가 -1되지만 
적비행기와 충돌시에도 health를 소모시키게 바꿔야한다고 생각합니다.

**추가적인 컨텍스트**

- [ ] 적비행기와 충돌 시 health -1시킨다.

**Comment by siroch** [comment]
이미 완료한 이슈입니다
