### ISSUE TITLE
[FEATURE] 게임 종료시 무적

### ISSUE THREAD

**Issue by minb234** [inureyes/gradios#246]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
적 비행기를 모두 처치하고 승리했다는 문구가 뜬 후  적이 쏜 bullet에 health가 0이 되면 
gameover가 뜹니다.

**어떤 해결책을 선호하는지 설명해주세요**
적 비행기를 모두 처치하면 player의 비행기가 무적이 되어 게임의 결과가 변경되지 않도록 수정
해야 합니다.

**추가적인 컨텍스트**

- [ ] 적 비행기를 모두 처치하면 player의 비행기가 무적이 되어 게임의 결과가 변경되지 않도록 수정

**Comment by siroch** [comment]
이 내용은 issue #101과 유사한 내용입니다.
