### ISSUE TITLE
[FEATURE] README.md에 학생 명단에 중복된 학생들이 있습니다.

### ISSUE THREAD

**Issue by wogns3623** [inureyes/gradios#249]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
README.md 파일의 학생명단에 중복되는 학생들이 있습니다.

**어떤 해결책을 선호하는지 설명해주세요**
README.md의 학생명단을 정리하였으면 합니다.

**고려했던 대안들에 대해 설명해주세요**
학생 명단을 역할, 이름 순서대로 정렬하고, 중복된 학생의 명단을 통합시킨다.

**추가적인 컨텍스트**
이 기능 추가 요청과 관련된 상황이나 스크린샷들을 추가해주세요.

**Comment by doublik** [comment]
제가할게요!

**Comment by wogns3623** [comment]
아직 중복된 학생이 있어 이슈를 재오픈합니다.
이 이슈는 제가 해결하겠습니다.
