### ISSUE TITLE
[BUG]폭팔이펙트가 제대로 발생하지 않는 버그

### ISSUE THREAD

**Issue by wogns3623** [inureyes/gradios#258]
**Describe the bug**
정상적인 폭팔 이펙트 후 두번째 폭팔 이펙트가 정상적으로 보이지 않는 버그가 있습니다.
두번째 이펙트는 폭팔 이펙트 프레임의 마지막 부분인 것으로 추정됩니다.

**To Reproduce**
1. 폭팔이펙트를 발생시킨다.
2. 두번째 폭팔 이펙트를 발생시킨다.
3. 두번째 폭팔 이펙트가 제대로 발생하지 않음

**Expected behavior**
모든 폭팔 이펙트가 정상적으로 끝까지 출력됨

**Screenshots**
스크린샷으로 제대로 드러나지 않아 찍지 않았습니다.

**Desktop (please complete the following information):**
 - OS: any
 - Browser: any
 - Version: any

**Additional context**
간단하게 폭팔이펙트의 킬타이머를 조금 늘리면 해결될 것 같습니다.

**Comment by siroch** [comment]
제가 하겠습니다.
