### ISSUE TITLE
[BUG]  마지막 한마리의 적이 남았을때 몸빵으로 죽이면 게임이 끝나지 않습니다.

### ISSUE THREAD

**Issue by AnOldStory** [inureyes/gradios#267]
**Describe the bug**
마지막 한마리의 적이 남았을때 몸빵으로 죽이면 게임이 끝나지 않습니다.

**To Reproduce**
1. 한마리 남을때까지 공격으로 부신다
2. 비행기로 남은 한마리의 적에게 부딪힌다
3. 게임이 안끝난다

**Expected behavior**
1. 한마리 남을때까지 공격으로 부신다
2. 비행기로 남은 한마리의 적에게 부딪힌다
3. 게임이 끝나야한다.

**Comment by doublik** [comment]
제가 한번 해보겠습니다.
