### ISSUE TITLE
[FEATURE]남아있는 목숨 비례 점수 변화를 줬으면 좋겠습니다.

### ISSUE THREAD

**Issue by siroch** [inureyes/gradios#271]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
게임을 더 완벽하게 플레이할수록 점수가 높아지는 시스템이 있어야 사람들이 더 게임에 몰두하게 될거라고 생각합니다.

**어떤 해결책을 선호하는지 설명해주세요**
남아있는 목숨*n의 점수를 추가해주는 방식

**고려했던 대안들에 대해 설명해주세요**
다른 대안이라하면 목숨이 줄을때마다 최종점수에서 일정 점수를 빼는 방식도 괜찮다고 생각합니다.

**Comment by HochulHwang** [comment]
제가 하겠습니다.
