### ISSUE TITLE
[FEATURE] 메뉴화면, 종료화면에 들어갈 이미지 만들어주세요.

### ISSUE THREAD

**Issue by doublik** [inureyes/gradios#273]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
현재 각 화면이 너무 허전합니다.
각 화면에 들어갈 백그라운드, 버튼이미지를 만들어주세요.
(현재 버튼이미지는 임시로 제작한 이미지입니다.)

**어떤 해결책을 선호하는지 설명해주세요**
게임에 어울리는 이미지제작

**고려했던 대안들에 대해 설명해주세요**

**추가적인 컨텍스트**
이 기능 추가 요청과 관련된 상황이나 스크린샷들을 추가해주세요.

**Comment by Rory0304** [comment]
제가 버튼 이미지와 게임 배경 이미지를 추가해보겠습니다.

**Comment by sersue** [comment]
제가 시작 메뉴화면 추가해보겠습니다.

**Comment by Darkcruel** [comment]
제가 시작 이미지 넣어보겠습니다.

**Comment by Darkcruel** [comment]
시작화면 추가는 refs #411 에서 완료하였습니다.

**Comment by Rory0304** [comment]
버튼 추가는 #471 에서 완료하였습니다.
