### ISSUE TITLE
[BUG] 마지막 적 처치시 게임이 멈춥니다.

### ISSUE THREAD

**Issue by siroch** [inureyes/gradios#284]
**Describe the bug**
마지막 적을 처치하기 직전, 게임이 멈춥니다. 약 50회 테스트 해보았고 50회 전부 게임멈춤현상이 일어났습니다.

**To Reproduce**
1. 한마리 적이 남을때까지 살아있는 상태로 적을 모두 처치한다.
2.마지막 적에게 총을 쏜다.
3.적에게 총이 닿기 전 게임이 멈춘다.

**Expected behavior**
1. 한마리 적이 남을때까지 살아있는 상태로 적을 모두 처치한다.
2.마지막 적에게 총을 쏜다.
3.적을 마저 처치한 후 issue #276, resolve #276 이 반영되어있으므로 계속해서 적이 생성되어야 함

**Screenshots**
![image](https://user-images.githubusercontent.com/39474054/56331073-c13d9180-61c5-11e9-870a-5754ddf6514f.png)

**Comment by sejin1031** [comment]
수정하겠습니다
