### ISSUE TITLE
[FEATURE] 플레이어의 스폰위치 고정하기

### ISSUE THREAD

**Issue by YunSungJu** [inureyes/gradios#286]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
게임을 재 시작하면 플레이어의 위치가 이전 게임에서의 마지막 위치로 설정이 되어있습니다. 재 시작을 하더라도 고정된 위치에서 스폰되도록 하는것이 바람직한 것 같습니다.

**어떤 해결책을 선호하는지 설명해주세요**
플레이어의 스폰위치를 고정하도록 합시다.

**고려했던 대안들에 대해 설명해주세요**

**추가적인 컨텍스트**

**Comment by wogns3623** [comment]
#94 이슈에서 이미 해결된 문제입니다. 현재 버전으로 실행시켜본 결과 정상적으로 동작합니다.
