### ISSUE TITLE
[FEATURE] 비행기 총알로 보라색 총알을 파괴할수있게 하겠습니다, score점수 크기를 줄이겠습니다.

### ISSUE THREAD

**Issue by moris0712** [inureyes/gradios#292]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
왼쪽상단에있는 scroe 점수가 크고,
만약 난이도가 높아질경우 비행기가 쏘는 총알로도 보라색 총알을 파괴할수있는것도 좋을것같습니다.

**어떤 해결책을 선호하는지 설명해주세요**
score 점수 폰트 크기를 줄이고
비행기 총알로도 보라색 총알을 파괴할수있게 고치겠습니다.

**고려했던 대안들에 대해 설명해주세요**
이미 고려해 보았던 다른 대안들에 대해 명확하고 간결하게 설명해주세요.

**Comment by wogns3623** [comment]
#229 와 같은 이슈로 보입니다

**Comment by moris0712** [comment]
의견 감사합니다

**Comment by doublik** [comment]
제가 하겠습니다.

**Comment by siroch** [comment]
어려움 난이도에서 총알을 피격해서 없앨 수 있는 기능이 추가될경우 난이도가 더 급증하는 상황이 벌어집니다.이 내용은 무기 업그레이드 및 광역피해입히는 스킬같은 기능이 없을경우 난이도를 높이기만 하는 기능인거 같습니다.
