### ISSUE TITLE
[FEATURE] 적 개체랑 닿을 때 죽지가 않습니다 

### ISSUE THREAD

**Issue by qaeqwg** [inureyes/gradios#307]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
적 개체랑 닿을 때 죽지가 않습니다 

**어떤 해결책을 선호하는지 설명해주세요**
적 개체랑 닿았을 때 죽을 수 있도록 해줬으면 좋겠습니다

**Comment by siroch** [comment]
현재 해결되어있는 내용입니다.
