### ISSUE TITLE
[FEATURE] 게임이 종료된 뒤에 엔터키를 통해서 다음화면으로 넘어갔으면 합니다. 

### ISSUE THREAD

**Issue by a6gongi** [inureyes/gradios#308]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
문제가 무엇인지 명확하고 간결한 묘사를 해 주세요.
게임이 끝난뒤엔 마우스클릭만 다음화면으로 넘어갈 수 있게 해주는데 번거로운 것 같습니다.

**어떤 해결책을 선호하는지 설명해주세요**
원하는 것에 대한 명확하고 간결한 설명을 추가해주세요.
마우스클릭 이외에도 다른 키를 배정하여 게임진행을 용이하게 해주면 좋을 것 같습니다.

**고려했던 대안들에 대해 설명해주세요**
이미 고려해 보았던 다른 대안들에 대해 명확하고 간결하게 설명해주세요.
스페이스바는 총을 쏘는 키라서 점수확인을 못하고 넘어갈 수 있으니 엔터키를 배정해준다. 
**추가적인 컨텍스트**
이 기능 추가 요청과 관련된 상황이나 스크린샷들을 추가해주세요.

**Comment by siroch** [comment]
게임이 종료되고 난 후 restart하고 menu 버튼 2개가 있고 추후 이슈에 있는 랭킹시스템이 적용될 경우를 생각해서 만들어야 할 것 같습니다.

**Comment by HochulHwang** [comment]
엔터키로 바로 시작이 가능하면 빠르게 테스트가 가능해서 좋을 것 같아 우선 추가하겠습니다.
