### ISSUE TITLE
[BUG] 스테이지 클리어 후 자체 폭발

### ISSUE THREAD

**Issue by HochulHwang** [inureyes/gradios#312]
#### 스테이지 클리어시 랜덤하게 비행기가 폭발하여 목숨이 줄어드는 현상이 일어납니다.  
총 12번의 게임, 75 스테이지를 실행한 결과, 아래와 같이 22번 스스로 폭발하는 현상이 나타났고 랜덤하게 이런 현상이 일어나는 것 같아 보입니다. (클리어시 폭발->X로 표기, 클리어시 정상 작동-> O로 표기, 게임 중 실수로 인한 폭발은 포함하지 않았음)  
>1: OOXXOOX 
>2: OOOOXX 
>3: OOXXX 
>4: XOOOX 
>5: OOX 
>6: OOOXXOX 
>7: XOOXX 
>8: OOOOOOOO 
>9: OOOOOO 
>10: OOXOOOXOOX 
>11: OOOXO 
>12: OOOOOXOO

**Comment by ppq0203** [comment]
플레이 해본결과 해결된것으로 보입니다.
