### ISSUE TITLE
[BUG] 사격시 서북방향으로 움직일 수 없습니다

### ISSUE THREAD

**Issue by roasted-penguin** [inureyes/gradios#313]
**Describe the bug**
사격하지 않을때는 조작에 이상이 없으나, 사격시에는 서북방향(방향키   '←' + '↑'  )으로 움직일 수 없다.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by siroch** [comment]
방금 확인해본 결과 제대로 플레이 됩니다.새로운 파일을 받고 실행해주세요.

**Comment by roasted-penguin** [comment]
새로운 파일 받아 실행해보았지만 안됩니다......
다른 맥에서는 제대로 플레이되는걸 확인했으나, 윈도우 기반인 제 노트북에선 돌아가지 않습니다.

혹시 다른 윈도우 분들도 위와 같은 버그 존재하는지 말해주세요.

**Comment by wogns3623** [comment]
아마도 키보드 설계상 특정 키들은 중복 입력이 불가능할 수 있는데 이러한 종류의 문제인 듯 싶습니다.
윈도우 10인 제 노트북 기준에서는 잘 동작합니다
