### ISSUE TITLE
[FEATURE] HEART를 추가하여 플레이어가 먹으면 Health를 하나늘리겠습니다

### ISSUE THREAD

**Issue by KRCHOIJUNHO** [inureyes/gradios#322]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
하트를 추가해서 체력을 늘려주면 더 재미있을거같습니다.

**어떤 해결책을 선호하는지 설명해주세요**
하트를 먹으면 체력을 늘려줍니다.

**고려했던 대안들에 대해 설명해주세요**
이미 고려해 보았던 다른 대안들에 대해 명확하고 간결하게 설명해주세요.

**추가적인 컨텍스트**
이 기능 추가 요청과 관련된 상황이나 스크린샷들을 추가해주세요.

**Comment by roasted-penguin** [comment]
슈퍼마리오의 빨강 코인에서 모티브를 따와, 랜덤한위치에 순차적으로 카운터를 생성하여 일정시간 내에 카운터 8개를 먹으면 목숨 1개를 지급하는 식으로 만드는것은 어떨까요?

**Comment by KRCHOIJUNHO** [comment]
그것도 좋은아이디어네요 근데 이미 해논게있어서 댓글 달아주신걸 issue로 추가하면 어떨까요?
