### ISSUE TITLE
[FEATURE] 적과 비행기가 닿을 때 Health가 감소했으면 좋겠습니다 

### ISSUE THREAD

**Issue by qaeqwg** [inureyes/gradios#327]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
보통 다른 탄막 슈팅 게임의 경우 적 기체와 닿을 경우 목숨이 깎입니다
우리의 게임도 그렇게 했으면 좋겠습니다 

**어떤 해결책을 선호하는지 설명해주세요**
적 개체와 닿을 때 HEALTH가 감소했으면 좋겠습니다

**Comment by HochulHwang** [comment]
지금도 적과 닿으면 Health가 감소하지 않나요? 최신 버전으로 git pull 해보시고 실행해보시면 좋을 것 같아요!

**Comment by qaeqwg** [comment]
아 그렇네요 감사합니다!
