### ISSUE TITLE
[BUG] 게임 종료시 점수가 살짝 치우쳐서 출력됩니다.

### ISSUE THREAD

**Issue by ChoiJunhee** [inureyes/gradios#328]
**Describe the bug**
게임 종료 후 나오는 점수가 중앙정렬이 아니라 좌측이나 우측으로 살짝 치우쳐서 출력됩니다.

**To Reproduce**

**Expected behavior**

**Screenshots**
![12341234](https://user-images.githubusercontent.com/43108674/56458982-90797a00-63c8-11e9-8bef-d67751db9fb2.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 73.0.3683.103

**Smartphone (please complete the following information):**

**Additional context**
아마... textalign을 손보면... 될 것 같습니다.

**Comment by HochulHwang** [comment]
해결했습니다.  
<img width="665" alt="Screen Shot 2019-04-21 at 12 57 34 AM" src="https://user-images.githubusercontent.com/31910827/56459616-fe29a400-63d0-11e9-8954-4ba2e9346825.png">
