### ISSUE TITLE
[FEATURE] 적의 총알을 맞췄을때 효과가 있었으면 좋겠습니다.

### ISSUE THREAD

**Issue by YimChonghyon** [inureyes/gradios#329]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
- 적의 총알을 맞췄을 때 아무런 효과 없이 적의 총알이 사라지기만 합니다. 

**어떤 해결책을 선호하는지 설명해주세요**
- 적의 총알을 맞췄을 때에도 폭발 이미지와 폭발음 등의 효과가 있었으면 좋겠습니다.

**Comment by HochulHwang** [comment]
효과 추가했습니다.
