### ISSUE TITLE
[FEATURE]적의 생성과 움직임이 다양했으면 좋겠습니다.

### ISSUE THREAD

**Issue by YimChonghyon** [inureyes/gradios#330]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
- 게임이 시작되었을 때 배치된 적들이 한 스테이지가 끝날 때 까지 앞, 뒤 이동만 합니다.

**어떤 해결책을 선호하는지 설명해주세요**

- 적들이 게임이 시작되었을때만 생성되는것이 아니고 시간에 따라 적이 계속 생성되었으면 좋겠습니다.

- 적들이 앞,뒤로만 움직이지 않고 다양한 움직임을 가졌으면 좋겠습니다.  
  (적들이각자 독립적인 움직임을 갖으면 더 좋을 것 같습니다.) 

- [x] 적들이 게임이 시작되었을때만 생성되는것이 아니고 시간에 따라 적이 계속 생성되게한다.
- [x] 적들이 앞,뒤로만 움직이지 않고 다양한 움직임을 갖게한다.

**Comment by HochulHwang** [comment]
적들의 움직임을 추가하였습니다.

**Comment by ppq0203** [comment]
적들의 움직임을 각자 다르게 추가하였습니다.

**Comment by ppq0203** [comment]
적들을 시간에따라 생성되게 수정하였습니다.
