### ISSUE TITLE
[FEATURE] 스테이지 정보가 있었으면 좋겠습니다.

### ISSUE THREAD

**Issue by YimChonghyon** [inureyes/gradios#331]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
- 지금은 한 스테이지가 끝나고 다음 스테이지로 넘어가도 몇번째 스테이지인지 알 수 없습니다.

**어떤 해결책을 선호하는지 설명해주세요**
- 스테이지에 대한 정보 (몇번째 스테이지인지 등) 가 스코어 옆에 표시되었으면 좋겠습니다.
- 스테이지가 끝나고 다음 스테이지로 넘어갈 때 스테이지 변화를 알려주는 효과음 또는 게임화면의 변화가 있었으면 좋겠습니다.

- [x] 스코어 옆에 게임 스테이지에 대한 정보 표시
- [x] 스테이지 변화를 알려주는 효과 추가

**Comment by HochulHwang** [comment]
관련 기능 추가했습니다.
