### ISSUE TITLE
[BUG] 하트로 인해 생긴 버그

### ISSUE THREAD

**Issue by siroch** [inureyes/gradios#340]
1. 특정 상황, 적에게 피격을 당함과 동시에 하트를 먹을경우 체력이 1칸 달기만 하는것을 발견했습니다. 이 상황에 대해 수십번의 테스트를 진행해본것은 아니라서 확정은 아니지만 확인이 필요한 사항인것 같습니다.

2. 체력이 줄어있는 상태에서 하트를 먹었을때 줄어든 위치에 채워지는것이 아닌 기존 위치의 왼쪽에 계속하여 쌓이는것을 보았습니다. 이 내용 역시 수정이 필요해 보입니다.

3. 이 내용은 버그는 아니지만 조정이 필요한 사항인거같아 넣었습니다. 하트의 이동속도를 난이도에 따라 차등 조절하는것이 좋다고 보여 내용을 넣어봅니다.

- [x] 1번 오류 해결
- [x] 2번 기능 수정
- [x] 3번 기능 수정

**Comment by KRCHOIJUNHO** [comment]
2번 같은 경우는 의도해서 한거기 때문에 버그가아니라 기능 수정으로 하는게 괜찮아보입니다.

**Comment by KRCHOIJUNHO** [comment]
1번  눈으로 보았을때 동시에 하트를 먹거나 총알을 맞았을순 있지만 둘의 시간차이는 명백히 존재하는 것 같아보입니다. 따라서 총알을 맞는게 더빠르다면 생명이 늘어나고 아니면 체력이 1칸달고 그러는거 같습니다. 특이한 케이스여서 확인이 어렵네요

**Comment by KRCHOIJUNHO** [comment]
3번은 제가하겠습니다.

**Comment by siroch** [comment]
수정했습니다.

**Comment by KRCHOIJUNHO** [comment]
3번 해결했습니다.

**Comment by ChoiJunhee** [comment]
1번의 경우 무적 상태에서 공격 키를 누른 상태로 하트가 안먹어지는것 같습니다... 무적 시간을 늘리고, 하트 출현 빈도를 높여 몇 번 테스트 해봤습니다.

**Comment by ppq0203** [comment]
2번이 오류가아니고 의도해서 한것이라고 말했는데 제생각엔 오류맞습니다.
![bug](https://user-images.githubusercontent.com/22339339/56577820-f7847200-6606-11e9-81a1-7a9543a9b50f.jpg)
지속적으로 반복시 체력이 보이지않습니다 따라서 2번은 제가 수정하겠습니다.
