### ISSUE TITLE
[FEATURE] 플레이어가 이동할 수 없는 위치에서 하트가 생성됨

### ISSUE THREAD

**Issue by siroch** [inureyes/gradios#363]
화면 테두리를 기준으로 이미지가 절반정도 잘린 상태로 하트가 생성되어 움직이는것을 보았습니다.
스테이지 27에서 발견해 너무 빠르게 지나가 스크린샷을 찍지는 못했습니다.

이 경우 하트가 생성되어도 먹지 못하는 현상이 생기게 됩니다.
시급한 사항은 아니지만 원활한 게임 진행을 위해선 고쳐져야하는 사항입니다.

- [ ] 플레이어가 지나가지 못하는 위치에 하트가 생성되는 내용 수정

**Comment by KRCHOIJUNHO** [comment]
해결하겠습니다.
