### ISSUE TITLE
[FEATURE] 체력이 더 많은 적을 만들면 좋을것 같습니다

### ISSUE THREAD

**Issue by roasted-penguin** [inureyes/gradios#365]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
작은 개체들만 있어서 심심합니다

**어떤 해결책을 선호하는지 설명해주세요**
몸집은 더 크지만 체력은 더 많은 alien을 만듭니다

**고려했던 대안들에 대해 설명해주세요**
일단 체력을 3정도로 해놓고 추후 기능을 넣도록 하는것이 좋을것 같습니다.

**추가적인 컨텍스트**

**Comment by siroch** [comment]
이슈 #324 에 속한 내용입니다

**Comment by wogns3623** [comment]
제가 해결하겠습니다.
