### ISSUE TITLE
[FEATURE] 적이 오른쪽에서 왼쪽으로 흘러갔으면 좋겠습니다.

### ISSUE THREAD

**Issue by mjkya** [inureyes/gradios#368]
**어떤 해결책을 선호하는지 설명해주세요**
현재 적들은 앞뒤를 왔다갔다 거리며 적들을 다 죽여야만 다음 스테이지로 갈 수 있습니다.
이것을 적들이 그냥 나타났다가 안 맞춰도 오른쪽에서 왼쪽으로 흘러가게끔 하면 좋겠습니다.

**고려했던 대안들에 대해 설명해주세요**
적들이 오른쪽에서 왼쪽으로 흘러가면서 추가적인 배경 오브젝트들도 흘러갔으면 좋겠습니다.

**Comment by KRCHOIJUNHO** [comment]
#351  확인부탁드려요

**Comment by mjkya** [comment]
넵 확인했습니다. 죄송합니다
