### ISSUE TITLE
새로운 디자인 추가 관련한 branch 생성

### ISSUE THREAD

**Issue by Rory0304** [inureyes/gradios#374]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
배경이나 게임 컨셉 공모와 관련된 새로운 디자인 추가가 이루어지고 있는 만큼, 게임에 쓰이고 있는 public/img에 이미지 파일을 넣기보다 새로운 branch를 만들어서 그 branch에 파일을 추가하는 편이 괜찮다고 생각합니다.

**Comment by sujeong1217** [comment]
제가 해결했습니다.
