### ISSUE TITLE
[FEATURE] 일시정지 중 배경음악이 멈췄으면 좋겠습니다.

### ISSUE THREAD

**Issue by sujeong1217** [inureyes/gradios#380]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
게임 중 일시정지를 했을 때 배경음악이 멈췄으면 좋겠습니다.

**어떤 해결책을 선호하는지 설명해주세요**
일시정지를 했을 때 배경음악이 멈췄으면 좋겠습니다.

**Comment by KRCHOIJUNHO** [comment]
제가 하겠습니다
