### ISSUE TITLE
[Feature] 목숨을 잃고 Heart를 먹으면 Health가 왼쪽으로 추가 됨

### ISSUE THREAD

**Issue by HochulHwang** [inureyes/gradios#391]
목숨을 잃고 Heart 먹기를 반복하면 Health가 아래 이미지와 같이 계속 왼쪽으로 추가됩니다. 초기 Health의 공간에 고정을 시키는 것이 보기에 좋을 것 같습니다.  

<img width="875" alt="Screen Shot 2019-04-22 at 2 03 54 AM" src="https://user-images.githubusercontent.com/31910827/56473280-cd666f00-64a3-11e9-8deb-bda7037ac166.png">

**Comment by siroch** [comment]
이슈 #340 에 같이 있는 내용입니당

**Comment by HochulHwang** [comment]
네 감사합니다 참고하겠습니다.
