### ISSUE TITLE
[BUG] 적들이 중복되어 출현합니다.

### ISSUE THREAD

**Issue by ChoiJunhee** [inureyes/gradios#392]
**Describe the bug**
적들이 겹쳐서 출현하는 버그가 있습니다.

**To Reproduce**

**Expected behavior**
적을 랜덤하게 출현시키는 과정에서 문제가 생긴 것 같습니다.

**Screenshots**
![123](https://user-images.githubusercontent.com/43108674/56485416-dc363b80-650e-11e9-9f67-584478460d6b.PNG)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
의도한 것은 아니라 생각되어 버그로 보고합니다.

**Comment by KRCHOIJUNHO** [comment]
제가 해결하겠습니다
