### ISSUE TITLE
[FEATURE] 위키의 설명을 추가하겠습니다.

### ISSUE THREAD

**Issue by ChoiJunhee** [inureyes/gradios#395]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
지금 위키에 나와있는 설명으로는 게임을 실행하기 어려운 부분이 있는 것 같습니다.

**어떤 해결책을 선호하는지 설명해주세요**
게임 실행을 위한 과정, 위키에 걸맞는 추가적인 정보가 필요하다 생각합니다.

**고려했던 대안들에 대해 설명해주세요**
 실행을 위한 설명을 추가할 예정입니다.

**추가적인 컨텍스트**
필요한 설명이 있으면 알려주세요.

**Comment by ChoiJunhee** [comment]
제가 하겠습니다

**Comment by JerryJang** [comment]
위키 이미지가 안보입니다.

**Comment by ChoiJunhee** [comment]
수정하겠습니다

**Comment by JerryJang** [comment]
해결한 것을 확인했습니다. ㅎㅅㅎ

**Comment by ChoiJunhee** [comment]
해결했습니다 ㅜㅜ
