### ISSUE TITLE
[BUG] 스테이지 종료 후 자체폭발 현상 #354참고

### ISSUE THREAD

**Issue by minkwns** [inureyes/gradios#397]
**Describe the bug**
전에 해결했던 스테이지 후 자체폭발 or 새로 생기는 enemy에 의해 죽는 현상이 다시 발생했습니다.

아마 어떤 분이 최신으로 fetch를 안하고 merge를 하셔서 전에 해결된 이 버그코드가 삭제된 것 같습니다.
확인 후 코드 수정 부탁드립니다.

#354 참고 부탁합니다.

**Comment by ppq0203** [comment]
플레이 해본결과 해결된것으로 보입니다.
