### ISSUE TITLE
[FEATURE] 스테이지별로 다른 BGM & 배경

### ISSUE THREAD

**Issue by sejin1031** [inureyes/gradios#399]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
- 현재 모든 스테이지가 같은 BGM과 같은 배경입니다.
**어떤 해결책을 선호하는지 설명해주세요**
- 스테이지별로 다른 배경, 다른 BGM을 사용하면 좋을 듯 합니다.
- 무수히 많은 스테이지 배경은 불가능하므로 몇개를 돌려쓰는 방식으로 합니다.
**고려했던 대안들에 대해 설명해주세요**
- 새로운 배경파일 추가
- 새로운 BGM 추가

**추가적인 컨텍스트**
이 기능 추가 요청과 관련된 상황이나 스크린샷들을 추가해주세요.

**Comment by JerryJang** [comment]
제가 비트를 찍겠습니다.

**Comment by duncan2121** [comment]
제가 이미지를 추가 하겠습니다.

**Comment by duncan2121** [comment]
추가 완료 했습니다.

**Comment by duncan2121** [comment]
비트가 너무 해결이 안되어 제가 해결하겠습니다.

**Comment by duncan2121** [comment]
추가 완료 했습니다.
