### ISSUE TITLE
[FEATURE] 처음 게임 시작할 때 조작방법에 대한 설명이 있으면 좋겠습니다.

### ISSUE THREAD

**Issue by JerryJang** [inureyes/gradios#406]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
게임의 기능이 추가되면서 조작 방법을 알지 못해 헤메는 사람이 생겨날 것 같습니다. 

**어떤 해결책을 선호하는지 설명해주세요**
게임을 처음 시작할 때 조작법 설명이 담긴 화면을 보여주었으면 좋겠습니다.

**고려했던 대안들에 대해 설명해주세요**
.

**추가적인 컨텍스트**
.

**Comment by mjkya** [comment]
제가 해보겠습니다.

**Comment by ppq0203** [comment]
제가 해보겠습니다.

**Comment by Darkcruel** [comment]
오탈자가 있어서 다시 올립니다.
