### ISSUE TITLE
[BUG] 스테이지 클리어 이후 하트 버그

### ISSUE THREAD

**Issue by ChoiJunhee** [inureyes/gradios#407]
**Describe the bug**
referenced : #397, #354, #340, #312 

**To Reproduce**
스테이지 클리어 후, 자폭 현상이 이뤄진 뒤로 하트가 먹어지지 않습니다.

**Expected behavior**
이 외에도 무적 상태에서 깜박일 때 하트가 먹어지지 않는 경우도 있었습니다.
(무적 시간을 늘려 테스트 해보았습니다)

**Screenshots**
![test](https://user-images.githubusercontent.com/43108674/56502843-b0d34100-654e-11e9-8d89-8871516ab652.PNG)

**Additional context**
live_count 가 증가하고 ship 이미지가 로드되지 않은 것인지, live_count 도 증가하지 않은 것인지 확실하지 않습니다.

확실한건 무적 시간과 관계가 있는 것 같습니다...

**Comment by ppq0203** [comment]
스테이지 클리어 이후로 자폭현상이 일어나도 하트가 먹어지는 것을 발견하였습니다. 제가 확인한 것은 처음 실행하는 이후로 1회 게임이 종료된뒤 그다음 게임부터 하트가 전혀 적용되지않습니다.

**Comment by wogns3623** [comment]
제가 하겠습니다
