### ISSUE TITLE
[BUG] 게임 실행이 안됩니다.

### ISSUE THREAD

**Issue by Darkcruel** [inureyes/gradios#408]
**Describe the bug**
게임 실행을 해도 검은 화면만 나옵니다.

**Screenshots**
<img width="943" alt="screenshot" src="https://user-images.githubusercontent.com/22339403/56503311-0a883b00-6550-11e9-9fc2-fb7ee32f13b0.png">

**Comment by ChoiJunhee** [comment]
파일을 새로 다운받아보세요

**Comment by JerryJang** [comment]
확인해 보겠습니다.

**Comment by AnOldStory** [comment]
제가해결하겠습니다
