### ISSUE TITLE
[FEATURE] 게임 시작화면이 좀 더 우주 같으면 좋겠습니다.

### ISSUE THREAD

**Issue by mjkya** [inureyes/gradios#411]
**어떤 해결책을 선호하는지 설명해주세요**
현재 시작 화면이 임시라 흰 바탕화면에 스타트 버튼만 있는데 시작 화면이 좀 더 우주스러우면 좋겠습니다.

**고려했던 대안들에 대해 설명해주세요**
자바스크립트를 잘 사용하여 움직이는 배경을 만들면 멋있을 것 같습니다.

**Comment by Darkcruel** [comment]
제가 해보겠습니다.
