### ISSUE TITLE
[FEATURE] 아이템 컨셉 통일

### ISSUE THREAD

**Issue by KRCHOIJUNHO** [inureyes/gradios#413]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
아이템 기능을 통일을 안하면 게임이 산만해질거 같습니다.

**어떤 해결책을 선호하는지 설명해주세요**
 지금까지 여러 아이템이 나왔는데요. 각각의 아이템의 컨셉을 통일했으면 좋겠습니다.
 예를 들어 바운스 기능을 한다고 하면 모든 아이템이 바운스 기능을 하도록 했으면 좋겠습니다.
 또한, 이미지도 비슷한 형식 통일했으면 좋겠습니다.
 예를 들어 하트는 하트 모양인데 speedup 같은 경우는 글씨로 써져있는데 이를 통일했으면 좋겠습니다.

**Comment by ppq0203** [comment]
speedup 경우에는 수정이 필요하다고 보입니다.
