### ISSUE TITLE
[FEATURE]적의 공격 강화

### ISSUE THREAD

**Issue by dury008** [inureyes/gradios#417]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
적이 총알을 앞으로만 쏴서 피하기가 쉬운것 같습니다.
적의 공격을 좀더 강화시켜서 피하기 어렵게 만드는것이 좋을것 같습니다.

**어떤 해결책을 선호하는지 설명해주세요**
적이 총알을 한번에 두개를 쏘게 하거나
적의 총알이 앞으로말고 대각선으로도 날라가게 하는것도 좋은 것 같습니다.

**고려했던 대안들에 대해 설명해주세요**
이미 고려해 보았던 다른 대안들에 대해 명확하고 간결하게 설명해주세요.

**추가적인 컨텍스트**
이 기능 추가 요청과 관련된 상황이나 스크린샷들을 추가해주세요.

**Comment by mjkya** [comment]
현재 적의 총알이 플레이어를 따라다니는 것으로 알고 있습니다.
플레이어가 아래에 있으면 총알도 아래로 쏴지고 플레이어가 위에 있으면 총알도 위로 날아옵니다.
다시 플레이 해 보시고 한 번 확인해보세요:)

**Comment by Darkcruel** [comment]
만약에 플레이어의 위치에 상관없이 적들이 총알을 여러방향으로 발사한다면 어떨까요?

**Comment by mjkya** [comment]
그것도 한 방법인 것 같습니다.
개인적으로 총알이 플레이어를 따라 오는게 게임 난이도를 높여서 더 재밌다고 생각은 됩니다.
