### ISSUE TITLE
[FEATURE] #413 아이템이 적을 죽이면 랜덤으로 나오는 방식으로 통일할까 하는데 어떻게 생각하시나요?

### ISSUE THREAD

**Issue by KRCHOIJUNHO** [inureyes/gradios#418]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
#413 에서와 같이 아이템 나오는 부분을 통일 할라고 합니다.

**어떤 해결책을 선호하는지 설명해주세요**
적을 죽였을때 아이템 랜덤으로 나오는 방식으로 통일 할까 합니다.

**고려했던 대안들에 대해 설명해주세요**
이미 고려해 보았던 다른 대안들에 대해 명확하고 간결하게 설명해주세요.

**추가적인 컨텍스트**
이 기능 추가 요청과 관련된 상황이나 스크린샷들을 추가해주세요.

**Comment by KRCHOIJUNHO** [comment]
별로면 댓글 달아주세요. 일단은 제가 하겠습니다.

**Comment by HochulHwang** [comment]
떠다니는 하트가 다섯개 모이면 필살기가 나가도록 만드는 건 어떨까요?

**Comment by KRCHOIJUNHO** [comment]
지금 commit 한 상황이 하트가 바운딩 되는걸 없애서 못할거 같습니다 ㅠㅠ

**Comment by HochulHwang** [comment]
네 알겠습니다!
