### ISSUE TITLE
[FEATURE] 하트가 너무 많이나옵니다

### ISSUE THREAD

**Issue by moris0712** [inureyes/gradios#419]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
하트가너무많이 나옵니다
하트를 다 못먹어서 하트가 맵에 부딪히면서 붕붕 떠다닙니다.
하트를 튕기지말고 없어지던가 하트수를 조정해야할것같습니다.

**Comment by KRCHOIJUNHO** [comment]
제가 해결하겠습니다.
