### ISSUE TITLE
[FEATURE] 설정 창이 있었으면 좋겠습니다.

### ISSUE THREAD

**Issue by moris0712** [inureyes/gradios#420]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
예를 들어 효과음 배경음 나누어서 on / off기능이나 
정지버튼을 누르면 아래같은 스크린샷이 뜨는데 새로운 창 보다는 게임내에서 정지되는 기능이 추가되었으면좋겠습니다.
**어떤 해결책을 선호하는지 설명해주세요**
원하는 것에 대한 명확하고 간결한 설명을 추가해주세요.

**고려했던 대안들에 대해 설명해주세요**
이미 고려해 보았던 다른 대안들에 대해 명확하고 간결하게 설명해주세요.

**추가적인 컨텍스트**
이 기능 추가 요청과 관련된 상황이나 스크린샷들을 추가해주세요.
<img width="657" alt="스크린샷 2019-04-23 오후 12 36 31" src="https://user-images.githubusercontent.com/22339727/56551861-76a48680-65c4-11e9-8136-65d2026906c3.png">

**Comment by zzangjames** [comment]
제가 하겠습니다.
