### ISSUE TITLE
[BUG] 아이템으로 무기 강화가 제대로 적용되지 않는 버그가 생겼습니다.

### ISSUE THREAD

**Issue by siroch** [inureyes/gradios#421]
**Describe the bug**
무기 강화 아이템을 4개를 먹었을 때 한번에 5발이 나갈때도 있지만 2발이 나갈때도 있고 1발이 나갈때도 있습니다. 이 사항을 고쳐주셨으면 합니다

**Comment by HochulHwang** [comment]
해결하였습니다. 무기는 우선 6발까지 나가도록 수정했습니다.
