### ISSUE TITLE
[BUG]맞아도 체력이 달지않는 버그가있습니다.

### ISSUE THREAD

**Issue by ppq0203** [inureyes/gradios#428]
체력이 3개라고 표시된상태에서 맞아도 체력이 달지않는 버그가있습니다.

**Comment by ppq0203** [comment]
제가 해결하겠습니다.

**Comment by KRCHOIJUNHO** [comment]
혹여나 하는마음에 제가 방금 commit해서 fetch 최신상태로 해주시고 commit부탁드려요

**Comment by ppq0203** [comment]
#428 Heartbug
로 수정하였습니다.
체력이 안다는것이아닌 오버해서차는 버그였습니다.
