### ISSUE TITLE
[FEATURE] 아이템 타격시 아이템 변경 기능

### ISSUE THREAD

**Issue by HochulHwang** [inureyes/gradios#431]
#### 아이템과 관련된 추가적인 기능 추가 요청입니다. #414 #416 #418 
아이템을 타격하거나 맞출시 아이템의 종류(목숨, 공격력 강화, 스피드 향상, 점수 획득 비율 증가, 필살기 등)가 변화하면 게임이 더욱 흥미롭고 간결해질 것 같습니다. 

- [ ] 아이템 변경 기능 추가

**Comment by KRCHOIJUNHO** [comment]
제가 하겠습니다.
