### ISSUE TITLE
[BUG]  총알이 일정수만큼 나가지않습니다.

### ISSUE THREAD

**Issue by moris0712** [inureyes/gradios#432]
**Describe the bug**
햄버거 4개를 먹어서 총알 5개가 쏴지는데
스크린샷처럼 5발씩 안나가는경우가있습니다.

**Screenshots**

<img width="895" alt="스크린샷 2019-04-23 오후 11 29 15" src="https://user-images.githubusercontent.com/22339727/56589182-b2b90500-661f-11e9-9302-0deee1011390.png">

**Comment by HochulHwang** [comment]
#421 에서 해결하였습니다. 아직 업데이트가 되지 않은 것 같습니다. Git pull 하셔서 가장 최근 버전으로 업데이트 하시면 될 것 같습니다 :)
