### ISSUE TITLE
[BUG] 다음 라운드로 진행될때마다 랜덤으로 목숨 1개씩 없어집니다.

### ISSUE THREAD

**Issue by moris0712** [inureyes/gradios#434]
**Describe the bug**
라운드가 진행될때 랜덤의 확률 (1/4정도)로 목숨이 한개씩 없어집니다.
기체 피격음을 독특한걸따로 넣어봐서 해보았는데 피격음이 나면서 목숨이 깎아지는걸로 보아 
다음 라운드로 진행될때 랜덤의 확률로 적이 바로앞에 생성되고, 그 적이 공격한걸로 목숨이 깎이는것같습니다.

**Comment by sejin1031** [comment]
#397 과 동일한 내용의 issue입니다.
