### ISSUE TITLE
[BUG] 크롬으로 플레이시 stage 6부터 소리가 들리지 않습니다.

### ISSUE THREAD

**Issue by mjkya** [inureyes/gradios#445]
**Describe the bug**
크롬으로 플레이시 stage 6부터 소리가 들리지 않습니다.

**To Reproduce**
Stage 6 played in Chrome

**Desktop (please complete the following information):**
 - OS: ios
 - Browser : chrome

**Comment by AnOldStory** [comment]
제가 해결하겠습니다
