### ISSUE TITLE
[FEATURE] 아이템을 총알로 쏘면 아이템이 플레이어 쪽으로 빠르게 이동합니다.

### ISSUE THREAD

**Issue by mjkya** [inureyes/gradios#446]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
아이템을 쏘면 아이템이 플레이어 쪽으로 빠르게 이동됩니다.

**어떤 해결책을 선호하는지 설명해주세요**
아이템을 쏴도 플레이어에게 다가오는 것이 아니라 그 자리에 있었으면 좋겠습니다.

**추가적인 컨텍스트**
![before](https://user-images.githubusercontent.com/39973760/56660106-b741f400-66d9-11e9-8d12-bd4ce53caa79.png)
![after](https://user-images.githubusercontent.com/39973760/56660113-bd37d500-66d9-11e9-83a7-c10e37eaa9e4.png)

플레이하는 도중 스크린샷을 찍어 명확하게 보이지는 않지만 아이템을 쏘면 아이템이 플레이어 쪽으로 빠르게 이동합니다.

**Comment by sejin1031** [comment]
제가 하겠습니다
