### ISSUE TITLE
[BUG] 무기 강화가 제대로 적용되지 않습니다.

### ISSUE THREAD

**Issue by siroch** [inureyes/gradios#451]
190425 오전 9시 45분 기준 패치 완료 후 실행해본 결과
무기 강화가 생성되어 먹었을때 잠시 무기강화가 진행되었다가 다시 원래 공격모드로 돌아오는것을 확인 했습니다.
// 이 내용은 방금 이슈에서 확인 했습니다. 하지만 무기 강화기능의 지속은 추후 게임 내용 추가가 될 경우 필수적이며 목숨을 잃을때마다 무기 강화가 초기화 되는 방식으로 다시 처리해야 할거 같습니다. 

또 적 처치시 그 위치에 아이템이 스폰되는것을 보고 먹어보았으나 어떤 상태의 아이템을 먹어도 변화하는 내용은 없었습니다.

#447  내용은 추후 게임 진행시 문제가 되는 상황입니다. 게임 난이도의 조절은 적의 개체수와 적의 체력, 공격 패턴으로 조절해야할 문제지 플레이어를 너프 시켜서 해결할 문제 아니니 다시 수정 바랍니다.

- [x] 이슈 #447 revert
- [x] 아이템이 제대로 적용되지 않는 버그 수정

**Comment by sejin1031** [comment]
이슈 #447은 다시 수정해서 고쳐놨고, 플레이어 피격 시 강화가 모두초기화되도록 수정했습니다.

**Comment by mjkya** [comment]
일단 무기 강화가 일정 시간이 지나면 사라지는 부분은 수정해 두었습니다. 그러나 현재와 같은 상황이면 stage30 만큼 가더라도 위부터 시작해서 아래로 총알을 한번 쭉 쏘면 3초안에 클리어가 됩니다. 적이 쏘는 총알 또한 강화된 무기로 다 없애버리기 때문에 플레이어가 공격에 맞아 무기가 리셋되는 현상은 거의 발생하지 않습니다. 현재 시중에서 플레이 되고 있는 게임들도 대부분의 스킬은 쿨 타임을 가지고 있습니다. 플레이어 피격 시 강화가 모두 초기화되는 것이 난이도 조절에 최선의 방법인지는 생각해 봐야 할 것 같습니다.

**Comment by siroch** [comment]
현재 게임은 단순 잡몹만 늘어나는 간단한 수준의 게임이라서 무기 강화를 하면 할수록 난이도가 급격하게 쉬워지게 됩니다. 하지만 현재 이 게임의 이슈에서 추가해주었으면 하는 사항들을 생각했을땐 단순 무기강화를 없애는것이 아닌 적의 개체수, 패턴, 강화된 적, 보스몹 등등을 만들어서 난이도를 조정하는게 맞다고 생각했습니다. 무기 강화의 지속시간을 주고자 하려면 특수 무기들을 만들고 그 무기들에 대해서 지속시간을 줘서 해결해야할것같습니다.
