### ISSUE TITLE
[BUG] 아이템이 점멸하는경우가있습니다.

### ISSUE THREAD

**Issue by moris0712** [inureyes/gradios#459]
**Describe the bug**
아이템드롭후 랜덤으로 바뀌는것은 의도한것인지는 모르겠지만
몇몇 아이템이 점멸하면서 아이템이 랜덤으로 바뀝니다.

**Comment by wogns3623** [comment]
#489 #446 등의 이슈와 비슷한 문제로 보입니다. 혹시 지금도 동일한 문제가 일어나는지 확인 부탁드립니다.

**Comment by ppq0203** [comment]
확인해본결과 해결된것으로 보입니다.
