### ISSUE TITLE
[FEATURE].idea 파일은 .gitignore 파일에 포함되어있는 파일이므로 삭제가 필요할 것 같습니다.

### ISSUE THREAD

**Issue by zzangjames** [inureyes/gradios#469]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
.idea 파일은 불필요한 파일로 .gitignore 파일에 포함되어 있으나 github repository에 올라와 있어서 commit 하는 과정에서 변화가 생깁니다. 

**어떤 해결책을 선호하는지 설명해주세요**
.idea 파일은 .gitignore 파일에 포함되어있으므로 github repository에서 삭제가 필요할 것 같습니다.

**고려했던 대안들에 대해 설명해주세요**
x

**추가적인 컨텍스트**
x

**Comment by AnOldStory** [comment]
제가 해결하겠습니다
