### ISSUE TITLE
[FEATURE] 버튼과 배경이 맞지 않는것 같습니다.

### ISSUE THREAD

**Issue by Darkcruel** [inureyes/gradios#471]
시작화면이나 종료 화면에서 어떤 버튼은 배경이 없는데
어떤 버튼은 하얀색 배경을 띄니까 약간 자연스럽지 않습니다.
모든 버튼이 배경이 없다면 좀더 보기 괜찮을것 같습니다.

**Comment by sujeong1217** [comment]
menu 버튼과 control 버튼을 바꿔보겠습니다

**Comment by Rory0304** [comment]
제가 start와 restart버튼 만들겠습니다.
