### ISSUE TITLE
[BUG] 대각선 방향으로 움직일때 속도가 더 빠른 버그

### ISSUE THREAD

**Issue by doublik** [inureyes/gradios#473]
**Describe the bug**
앞뒤, 위아래로 움직일때 속도가 100이라고 하면
대각선으로 움직일때는 속도가 100*루트2 로 적용되어 움직입니다.

**To Reproduce**

**Expected behavior**
대각선 방향으로 움직일때도 속도가 100으로 이동할 수 있게 해결.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sejin1031** [comment]
해결했습니다
