### ISSUE TITLE
[FEATURE] control 버튼 누를때, 이미지가 닫히는 기능도 있었으면 좋겠습니다.

### ISSUE THREAD

**Issue by Rory0304** [inureyes/gradios#476]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
현재 시작화면의 control 버튼을 누르면, 
![image](https://user-images.githubusercontent.com/42709747/56866995-0b6f1000-6a1b-11e9-88d8-f6bc6daeec86.png)
이런식으로 이미지가 나오고 이 이미지를 다시 닫을 수 있는 방법이 없습니다. 

**어떤 해결책을 선호하는지 설명해주세요.**
이미지를 다시 클릭하면 사진이 닫히는 기능을 추가하는 방법이 있습니다.

**Comment by HochulHwang** [comment]
시작화면의 control 버튼과 게임 중 설정 버튼을 ESC로 닫으면 편할 것 같습니다.

**Comment by moris0712** [comment]
해결하였습니다.
