### ISSUE TITLE
[FEATURE]button 위치 조정

### ISSUE THREAD

**Issue by sujeong1217** [inureyes/gradios#477]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
버튼의 모양을 바뀌면서 위치가 애매해 졌습니다.
중앙으로 바뀌면 좋을거 같습니다.

**어떤 해결책을 선호하는지 설명해주세요**
버튼의 위치를 중앙으로 바꾸면 좋을거 같습니다.

**추가적인 컨텍스트**
<img width="1182" alt="스크린샷 2019-04-29 오전 1 06 04" src="https://user-images.githubusercontent.com/43164999/56867142-eaa7ba00-6a1c-11e9-979e-e8cdcbba263f.png">

**Comment by HochulHwang** [comment]
수정했습니다.  
<img width="896" alt="Screen Shot 2019-04-29 at 1 36 12 AM" src="https://user-images.githubusercontent.com/31910827/56867357-3a878080-6a1f-11e9-969d-283ec74e3444.png">
