### ISSUE TITLE
[BUG] 아이템 위치 변경 버그

### ISSUE THREAD

**Issue by duncan2121** [inureyes/gradios#489]
**Describe the bug**
아이템이 필드에 생성되어 있을 때 총을 쏘게 되면 총을 쏜 위치로 아이템의 위치가 변경되는 버그가 있습니다. 이를 아이템 원래 위치에 가만히 존재하도록 고쳐주세요.

**Comment by HochulHwang** [comment]
타격시 움직이지 않도록 수정했습니다.

**Comment by wogns3623** [comment]
아직도 아이템의 아래부분을 맞추면 아이템이 아래로 이동합니다.
근본적인 문제해결이 되지 않고 있어 제가 해결해보겠습니다.
