### ISSUE TITLE
[FEATURE] Physics 변경 요청

### ISSUE THREAD

**Issue by doublik** [inureyes/gradios#490]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
현재 게임의 physics 는 ARCADE입니다. AABB 방식이라 정확한 Hitbox구현이 어렵습니다.
P2JS로 하면 Polygon을 사용해 더욱더 정교한 Hitbox구현이 가능할 것이고, 그에따른 다양한 공격패턴들도 가능할 것같습니다.

**어떤 해결책을 선호하는지 설명해주세요**
physics 를 P2JS 로 바꾸길 원합니다.

**Comment by wogns3623** [comment]
후에 여러가지 적들이나 보스를 구현하려면 필수적으로 physics를 변경하는것이 맞다고 생각합니다.
