### ISSUE TITLE
[Feature]아이템이 움직였으면 좋겠습니다

### ISSUE THREAD

**Issue by dury008** [inureyes/gradios#497]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
아이템 생성시 제자리에만 있어서 아이템을 먹기가 힘들때가 있습니다
아이템이 움직였으면 좋겠습니다.

**Comment by HochulHwang** [comment]
#489 의 의견과 어느 정도 충돌이 있는 것 같습니다.

**Comment by duncan2121** [comment]
아이템이 움직인다는게 총을 쏘는 위치를 따라가는게 아니라 랜덤하게 움직이는걸 말하는 것 같습니다.

**Comment by wogns3623** [comment]
지금도 아이템이 총에 맞기 전까지는 움직입니다. 이는 아이템이 총에 맞았을 때 새로운 아이템을 생성하면서 기존 아이템의 위치와 속도가 사라지기 때문에 그렇습니다.

**Comment by wogns3623** [comment]
#489를 수정하면서 좀 더 확실히 아이템이 움직이도록 같이 수정하였습니다.
