### ISSUE TITLE
[BUG]목숨이 감소되면 획득점수가 감소되는 버그가 존재합니다.

### ISSUE THREAD

**Issue by ppq0203** [inureyes/gradios#499]
목숨이3개일때 점수가 60점
목숨이2개일때 점수가 40점
목숨이1개일때 점수가 20점씩 획득됩니다.

**Comment by wogns3623** [comment]
버그가 아닙니다. #271 이슈에서 이미 토의되어 바뀐 내용입니다. 이슈 올리시기전에 한번만 찾아봐주시면 감사하겠습니다
