### ISSUE TITLE
[FEATURE]아이템이 총알과 부딪혔을때 변하는데 딜레이가 생겼으면 좋겠습니다.

### ISSUE THREAD

**Issue by ppq0203** [inureyes/gradios#500]
슈팅게임 특성상 계속 공격키를 누르고있는데 이로인해 아이템이 계속변경되는게 별로 안좋아보입니다. 따라서 아이템과 총알이 부딪혀도 아이템이 변경되지 않았으면합니다.

**Comment by siroch** [comment]
아예 변경이 되지 않는것보단 딜레이없이 계속 변경되는것을 막고 변하는거에 대해 딜레이를 주는건 어떨까요?

**Comment by wogns3623** [comment]
아니면 아이템을 변경할 수 있는 최대 횟수를 정해놓는것은 어떨까요?
최대 변경 횟수를 넘어서서 아이템에 총알을 쏘면 총알이 아이템을 관통하도록 하는 방식으로 구현할 수 있을 것 같습니다.

**Comment by ppq0203** [comment]
횟수보다는 처음 말해주신 한번바뀌는데 딜레이 생성이 더 좋은것같습니다.

**Comment by ppq0203** [comment]
제가 하겠습니다.
