### ISSUE TITLE
[BUG] 스테이지 넘어갈때 적이 플레이어 위치에 생성되어 체력이 다는 버그가 아직 고쳐지지 않았습니다.

### ISSUE THREAD

**Issue by siroch** [inureyes/gradios#503]
#397  
#354 
#312 

이 이슈들중 1개는 해결 2개는 아직 등록되어있는 이슈입니다.
이 현상으로 인해 높은 스테이지에 진입하지 못해 다른 버그들을 발견해내지 못하는 현상이 일어나 게임 제작에 문제가 있을 수 있어 다시 올립니다.
스테이지 넘어갈때 무적 or 플레이어 위치에 적 리스폰 위치에 제한을 두는것으로 해결하는것이 어떨까요?

**Comment by AnOldStory** [comment]
제가 해보겠습니다

**Comment by wogns3623** [comment]
제가 전부터 하다가 방금 해결했는데 제가 혹시 이 이슈를 맡아도 될까요?

**Comment by AnOldStory** [comment]
넵 알겠습니다!
