### ISSUE TITLE
[FEATURE]4.30 15:52 기준 아이템이 생성되지 않습니다.

### ISSUE THREAD

**Issue by siroch** [inureyes/gradios#504]
확률이 매우 낮아서 생기는 현상이라면 확률을 조정해야하는 문제이며
확률이 매우 낮지 않은 상황이라면 현재 고쳐야 할 버그입니다.

만약 확률이 매우 낮아 생기는 현상이라면 수정하겠습니다.

//수정

**Comment by wogns3623** [comment]
아이템 드롭 확률이 이전과는 다르게 계산되어 확률이 낮아진 듯 합니다. 확률을 높였을 때는 아이템이 정상적으로 등장합니다
