### ISSUE TITLE
[FEATURE] 음악 on off 하면 바로 적용시켜서 바뀐 상태를 알수있게 하기

### ISSUE THREAD

**Issue by akalswl14** [inureyes/gradios#511]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
음악이 켜져있는데 게임을 하다가 환경설정을 눌러 음악 재생의 유무를 변경하고 싶을때, 예를 들어 off를 적용했을때, 이게 적용되었는지 바로 알수가 없습니다. 버튼을 눌리는 느낌(눌렀을때 버튼의 색깔이 변한다던지)이 없어 처음 게임을 실행할때 여러번 누른 경험이 있어 이슈를 작성합니다.

**어떤 해결책을 선호하는지 설명해주세요**
게임하다가 환경설정 눌렀을때 음악 on off 하면 바로 적용시켜서 바뀐 상태를 알수있게 하기

**고려했던 대안들에 대해 설명해주세요**
환경설정에서 게임에서의 배경음악을 따라가되, 환경설정 화면에서는 볼륨을 좀 작게하고, on상태에서 off상태로 변경하면 환경설정의 음악도 같이 꺼지면서 적용상태를 반영했으면 좋겠습니다.

**추가적인 컨텍스트**
.

**Comment by moris0712** [comment]
제가하겠습니다
