### ISSUE TITLE
[FEATURE] 볼륨 개별 조절

### ISSUE THREAD

**Issue by akalswl14** [inureyes/gradios#512]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
본 게임에는 볼륨 조절 기능이 없습니다. 컴퓨터 볼륨으로 조절해야합니다. 개인에 따라 두 음의 볼륨에 따라 차별적으로 조종하기를 원할 수 있습니다.

**어떤 해결책을 선호하는지 설명해주세요**
환경설정에서 효과음과 배경음악을 따로 조절할 수있도록 기능이 추가되었으면 좋겠습니다.

**고려했던 대안들에 대해 설명해주세요**
.
**추가적인 컨텍스트**
![image](https://user-images.githubusercontent.com/42285463/57007164-90c41180-6c21-11e9-9045-361be3b5e037.png)

이렇게 개별적으로 볼륨을 조절할 수있는 슬라이더 형식이면 좋을 것 같습니다.

**Comment by pbt98** [comment]
제가 해결해보겠습니다.

**Comment by pbt98** [comment]
죄송하지만 슬라이더 형식으로는 구현하지 못했습니다. 혹시 이미지 저작권 관련 문제가 해결되어있는 이미지가 있다면 알려주세요.
