### ISSUE TITLE
[FEATURE] 게임을 계속 진행할때 카운트하기

### ISSUE THREAD

**Issue by akalswl14** [inureyes/gradios#513]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
게임 중 환경설정에서 변경을하고 resume을 누르게 되면 바로 게임이 시작하게됩니다. 이보다는 3초정도 대기시간을 가지고 시작한다면 사용자들이 더 편할 것 같습니다.

**어떤 해결책을 선호하는지 설명해주세요**
환경설정에서 resume할때 3, 2, 1의 숫자를 카운팅하는 대기화면을 표시한뒤 계속하게 하기

**고려했던 대안들에 대해 설명해주세요**
.

**추가적인 컨텍스트**
![image](https://user-images.githubusercontent.com/42285463/57007332-c7e6f280-6c22-11e9-96f9-8b6e78637d69.png)
이런 느낌인데 이미지가 좀 무언가,,, 부족해 보이네요..! 여튼 위게임과 같이 게임을 이어서 시작하기전 정지시키고 3, 2, 1 을 띄우고자 합니다.

**Comment by sejin1031** [comment]
제가 하겠습니다

**Comment by ppq0203** [comment]
3초 정지시키는것은 추가하였습니다.

**Comment by ppq0203** [comment]
해결했습니다
