### ISSUE TITLE
[FEATURE] MainMemu 를 눌렀을때 확인창이 떳으면 좋겠습니다.

### ISSUE THREAD

**Issue by wangjh789** [inureyes/gradios#531]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
플레이하다가 resume 을 눌러야 하는데 mainmenu 를  누르는 일이 종종 있을 수 있을 것
같습니다.

**어떤 해결책을 선호하는지 설명해주세요**
설정창에서 mainmenu 를 눌렀을 시 
'정말 게임에서 나가시겠습니까? (진행 중인 데이터는 저장되지 않습니다.)' 라고 묻는 확인창을 추가했으면 합니다.   

**추가적인 컨텍스트**
<img width="600" alt="스크린샷 2019-05-02 오후 2 10 38" src="https://user-images.githubusercontent.com/19744909/57057515-3b046d80-6ce4-11e9-9995-ae41d0830237.png">

**Comment by moris0712** [comment]
제가하겠습니다
