### ISSUE TITLE
[FEATURE] 아이템 을 좀 더 수월하게 먹었으면 합니다.

### ISSUE THREAD

**Issue by wangjh789** [inureyes/gradios#533]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
현재 아이템이 맵 경계로 나가버리면 없어집니다. 

**어떤 해결책을 선호하는지 설명해주세요**
저 같은 똥손이 좀 더 쉽게 아이템을 먹었으면 합니다.

**고려했던 대안들에 대해 설명해주세요**
아이템이 등장하여 맵 경계에 부딪히면 튕기고, 5~7초 정도 있다가 사라지는 방식이 좋을 것 같습니다.

**Comment by pbt98** [comment]
제가 해결하겠습니다.
