### ISSUE TITLE
[FEATURE] 적의 등장 패턴 수정

### ISSUE THREAD

**Issue by ijehyunpark** [inureyes/gradios#536]
현재 적이 스테이지가 넘어갈 때 우측 화면상에서 무작위로 생성되는데 이 경우 플레이어 비행기의 활동 반경을 좌측 화면상으로 축소시키고 갑작스러운 적의 생성에 당황할 수 밖에 없습니다. 
따라서 적이 우측 화면 밖에서 안으로 들어오는것처럼 보이도록 수정해 이를 보안하고, 우주 공간을 여행한다는 느낌을 살릴 수 있을 겁니다.

**Comment by ppq0203** [comment]
현재 코드를 받아오시면 우측화면밖에서 안으로 들어오는것처럼 수정되었습니다. #330
