### ISSUE TITLE
[BUG] 음악이 겹쳐서 재생됩니다

### ISSUE THREAD

**Issue by tutu772** [inureyes/gradios#553]
현재 메인화면에서 바로 게임을 시작했을 시에는 별다른 문제는 없습니다.
하지만, control 버튼을 누르고 게임을 시작했을 경우, 음악이 겹쳐서 들리는 문제가 발생합니다.

[버그 영상](23초때부터 버그나옴)
https://www.youtube.com/watch?v=FRY101-r3fQ

**Comment by moris0712** [comment]
제가해결하겠습니다.
