### ISSUE TITLE
[FEATURE] 남은 적의 수 표시

### ISSUE THREAD

**Issue by ijehyunpark** [inureyes/gradios#554]
스테이지에 할당된 모든 적을 잡을 때까지 다음 스테이지로 넘어가지 않는데 남은 적의 수를 표기하여 플레이어가 다음 스테이지로 넘어가기 위한 조건을 쉽게 인지할 수 있도록 하는 것이 좋을 거 같습니다.

**Comment by moris0712** [comment]
제가 하겠습니다

**Comment by moris0712** [comment]
해결하였지만 900x600 창밖에 생성되어있는 적도 count됩니다 추후 다시 refactoring하겠습니다
