### ISSUE TITLE
[BUG] 게임 시작하고 0.5초 정도 뒤에 게임이 멈춥니다.

### ISSUE THREAD

**Issue by jiho5993** [inureyes/gradios#561]
현재 최신버전을 실행시켜보면 게임이 시작하고 나서 0.5초정도 뒤에 게임 전체가 멈춥니다.

![KakaoTalk_Photo_2019-05-03-13-53-13](https://user-images.githubusercontent.com/42717320/57120257-1d4e0b80-6dab-11e9-9b35-caa42b9fab42.png)

**Comment by siroch** [comment]
제가하겠습니다
