### ISSUE TITLE
[BUG] 왼쪽위 대각선으로 이동이 되지 않습니다.

### ISSUE THREAD

**Issue by Burusk** [inureyes/gradios#565]
현재 오른쪽 아래, 왼쪽 아래, 오른쪽 위로의 대각선이동은 자유롭지만, 왼쪽 위로 대각선이동을 하려고 하면 왼쪽으로만 이동하거나 위쪽으로만 이동합니다.

**Comment by tutu772** [comment]
저번에 비슷한 이슈가 올라왔었는데, 개인 노트북 키보드 문제라고 합니다.
