### ISSUE TITLE
[FEATURE] 개발할때 불편한 점을 최소화 시킬 수 있게 할 수 있는 방법을 제안하고자 합니다.

### ISSUE THREAD

**Issue by jiho5993** [inureyes/gradios#569]
개발을 할때 불편한점이 여러모로 있는것 같아 불편한점을 최소화 할 수 있게 방법을 제안하고자 합니다.
1. npm install, npm start 명령어를 입력하고 주소창에서 실행시키는 방법보단 명령어 실행시 바로 게임이 브라우저에서 작동될 수 있게 하였으면 좋겠습니다.
2. 코드를 수정할시 브라우저가 자동으로 새로고침을 할 수 있게 하였으면 좋을것 같습니다.

**Comment by AnOldStory** [comment]
제가 하겠습니다
