### ISSUE TITLE
[BUG] 게임 일시정지 후 다시 시작시의 버그

### ISSUE THREAD

**Issue by pbt98** [inureyes/gradios#573]
**Describe the bug**
일시 정지후 다시 시작할때 카운트가 다 지나가기 전에 다시 일시정지 매뉴를 열면 카운트가 멈추지 않고 계속 흘러가서 게임이 시작되는 버그

**To Reproduce**
1. 게임의 일시 정지 매뉴로 들어간다.
2. 게임을 재개한다.
3. 타이머가 다 되기 전에 일시정지 매뉴로 다시 들어간다.
4. 타이머가 멈추지 않는다.

**Expected behavior**
타이머가 다시 셋팅된후, 사용자 입력이 있기 전까지 게임이 재개되면 안된다.

**Screenshots**
![스크린샷 2019-05-03 오후 9 30 21](https://user-images.githubusercontent.com/35721041/57137474-f0214d80-6dea-11e9-85ba-3e431c4d5f5f.png)

**Desktop (please complete the following information):**
 - OS: Mac OS 10.14.4
 - Browser Safari
 - Version 12.1

**Comment by pbt98** [comment]
제가 해결하겠습니다.

**Comment by tutu772** [comment]
제가 해결하겠습니다!
