### ISSUE TITLE
[BUG] 실행 시간에 따른 성능 저하 문제

### ISSUE THREAD

**Issue by pbt98** [inureyes/gradios#601]
**Describe the bug**
* 오래 플레이하거나 다시 시작 이나 메인 매뉴로 돌아갔다 다시 게임을 할때 성능이 눈에 띄게 저하됩니다.

**To Reproduce**
1. 게임 시작
2. 일시 정지 매뉴 접근
3. 다시 시작
4. 성능 저하 현상

**Expected behavior**
처음 켰을때와 같은 성능을 보여줘야합니다.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser chrome
 - Version 62

**Comment by wogns3623** [comment]
성능 저하의 원인은 사운드를 플레이해줄때마다 새로 사운드를 추가하던 코드가 원인인 것으로 보입니다

**Comment by AnOldStory** [comment]
제가 해결하겠습니다.
