### ISSUE TITLE
[FEATURE]아이템 획득 효과음 추가

### ISSUE THREAD

**Issue by sujeong1217** [inureyes/gradios#602]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
생명, 무기 외의 아이템이 획득된 것인지 사라진 것인지 확인이 어려워 아이템을 획득 하였을 때 효과음이 생겼으면 좋겠습니다.

**어떤 해결책을 선호하는지 설명해주세요**
공격 효과음과는 다른 효과음이 났으면 좋겠습니다.

**Comment by Darkcruel** [comment]
특정 아이템 획득 소리가 안나서 추가해서 다시 올립니다.
