### ISSUE TITLE
[BUG] 설정창 메인메뉴로 가시겠습니까에서 뒤에 있는 설정창이 클릭됩니다.

### ISSUE THREAD

**Issue by AnOldStory** [inureyes/gradios#607]
설정창 메인메뉴로 가시겠습니까에서 뒤에 있는 설정창이 클릭됩니다.

메인메뉴로 가시겠습니까 에서는 그 뒤 설정창에 있는 기호들이 클릭되면 안됩니다.

![aasd](https://user-images.githubusercontent.com/27149435/57230505-7770fa00-7053-11e9-96e2-a9691ebbb056.gif)

**Comment by pbt98** [comment]
제가 해결하겠습니다.
