### ISSUE TITLE
[BUG] 게임 경과 시간에 대한 오류

### ISSUE THREAD

**Issue by jiho5993** [inureyes/gradios#611]
설정창에서 메인메뉴로 돌아가는 창을 띄우고 no를 선택한 뒤에 게임을 다시 재개하면 게임 경과 시간이 다시 1초로 변하는 현상이 발생합니다.
![스크린샷 2019-05-07 오후 1 39 17](https://user-images.githubusercontent.com/42717320/57272209-c196c180-70cd-11e9-80d7-3d8574b4049f.png)

**Comment by doublik** [comment]
ㅔ가하겠습니다.

**Comment by BS00000001** [comment]
제가 해결하겠습니다.

**Comment by BS00000001** [comment]
제가 해결하겠습니다

**Comment by BS00000001** [comment]
제가 해결하겠습니다.
