### ISSUE TITLE
[BUG] 스테이지가 어느 정도 올라가면 소리가 안나옵니다.

### ISSUE THREAD

**Issue by jaehyeon99** [inureyes/gradios#620]
스테이지가 올라가서 적들이 많이 나와 피격 되는 소리가 많이 나올 때 버그가 발생하여 소리가 나오지 않습니다.

**Comment by BS00000001** [comment]
피격되는 소리가 나오지 않는다는 것인가요??
아니면 배경음악이 나오지 않는다는 것인가요??

**Comment by jaehyeon99** [comment]
이슈 #659 번과 겹칩니다. 해결했습니다.
