### ISSUE TITLE
[FEATURE]시작화면에서 help 부분을 넣어  게임에 대한 간략한 설명을 넣었으면 합니다.

### ISSUE THREAD

**Issue by jaehyeon99** [inureyes/gradios#622]
게임 시작 화면에서 control 뿐만 아니라 아이템에 대한 설명이나 게임에 대한 전반적인 설명을 넣어주었으면 합니다.

**Comment by moris0712** [comment]
제가하겠습니다

**Comment by moris0712** [comment]
한글로 text를 쓰려다가 깨진다는 의견이있어서 이미지로 넣었습니다
혹시 수정사항이있을시, 말씀드리면 제가 수정하겠습니다.

**Comment by jaehyeon99** [comment]
여러가지 아이템이  추가됨으로 써  설명 되지 않는 아이템도 있고 무적 아이템의 경우 설명에는 15초 무적이라고 나와있지만 실제로는 5초 정도 밖에 되지 않습니다.

**Comment by moris0712** [comment]
오늘 새벽에 코드가 분할되면서 관통 아이템 쉴드 아이템 변경등 많은 코드수정이일어났습니다
쉴드 아이템도 한 종류입니다  아이템 기능이 완전 바뀌었습니다
제가 분할한게 아니여서 코드를 다시 이해하는데 시간이 걸리니 기능을 정리해주시면 수정하겠습니다

**Comment by jaehyeon99** [comment]
제가 해결하겠습니다.
