### ISSUE TITLE
[BUG] 게임 종료 후 플레이타임 00:01초로 초기화

### ISSUE THREAD

**Issue by roasted-penguin** [inureyes/gradios#628]
**Describe the bug**
적에게 피격등으로 사망 후 게임 종료시,  플레이타임이 00:01초로 초기화됩니다.

**To Reproduce**
시간 측정함수 관련 조정이 필요할 것으로 보입니다.

**Screenshots**

목숨 1, 피격전
![image](https://user-images.githubusercontent.com/43606521/57344344-d92f8200-7181-11e9-88be-aa139e330a1a.png)

피격후
<img width="681" alt="bug2" src="https://user-images.githubusercontent.com/43606521/57344387-054b0300-7182-11e9-9e68-d2018c1b4d2e.png">

**Comment by Darkcruel** [comment]
종료되고 나서도 시간초기화가 아니라 유지되도록 하였습니다.
