### ISSUE TITLE
[FEATURE] You died 라는 문구가 있었으면 좋겠습니다.

### ISSUE THREAD

**Issue by wangjh789** [inureyes/gradios#638]
3회이상 피격 되고 게임이 종료되면 스코어만 뜨는게 너무 허전해 보입니다.
게임오버, 유다이 등 좀 더 화면을 채울 수 있는 문구 같은게 필요할 것 같습니다.
(추가적으로 스코어외에도 플레이시간도 같이 나오면 좋을꺼 같습니다.)
<img width="200" alt="스크린샷 2019-05-08 오후 9 26 53" src="https://user-images.githubusercontent.com/19744909/57375628-e035af00-71d8-11e9-836e-a0a7392916b6.png">
<img width="200" alt="스크린샷 2019-05-08 오후 9 29 03" src="https://user-images.githubusercontent.com/19744909/57375643-e6c42680-71d8-11e9-85d2-c54d70c43f9f.png">

**Comment by BS00000001** [comment]
제가 해결하겠습니다.
