### ISSUE TITLE
[BUG] 적이 생성되지 않는 버그

### ISSUE THREAD

**Issue by HochulHwang** [inureyes/gradios#644]
적이 초반에 생성되다가 후에 시간이 지나도 생성되지 않는 버그가 발견됩니다. 비행기 두 종류 모두에서 이런 현상이 발견되며 6번 플레이중 4번 이런 현상이 일어났습니다. 

<img width="495" alt="Screen Shot 2019-05-09 at 12 46 01 AM" src="https://user-images.githubusercontent.com/31910827/57389399-09643880-71f5-11e9-9cb8-3652b434506b.png">

**Comment by BS00000001** [comment]
제가 해결하겠습니다

**Comment by BS00000001** [comment]
초반에만 이런 현상이 발생하나요??

**Comment by BS00000001** [comment]
제가 계속 플레이해보았는데 이러한 버그가 발생하지 않았습니다.
혹시 다시 나타난다면 코멘트를 달아주세요.

**Comment by BS00000001** [comment]
지금 그런 현상이 발견되어서 고치겠습니다.
