### ISSUE TITLE
[FEATURE] 이미지 추가 요청 - 수정

### ISSUE THREAD

**Issue by siroch** [inureyes/gradios#651]
![image](https://user-images.githubusercontent.com/39474054/57420666-8d451180-7243-11e9-9615-a5b7d7d5887d.png)

무기 기능에 맞는 디자인을 요청합니다.

**Comment by siroch** [comment]
버그가 아니라 단지 추가되어있지 않는거같아 수정합니다.

**Comment by siroch** [comment]
#480  이슈와 연관

**Comment by dudejrs** [comment]
제가 하겠습니다!

**Comment by siroch** [comment]
#678 이 진행된 관계로 전체 이슈로 다시 수정하였습니다
