### ISSUE TITLE
[BUG] 현재 게임시작 시 기체 선택할때 기체의 크기 문제

### ISSUE THREAD

**Issue by sejin1031** [inureyes/gradios#661]
**Describe the bug**
- 현재 게임 시작할 때 기체를 선택하는 화면에서 기체 하나가 너무 크게 나오고, 위치 또한 미적으로 좋지 않습니다.
**To Reproduce**
- 두 번째 기체의 크기를 조정하고 좌표만 약간 수정해줍니다.

**Expected behavior**

**Screenshots**
![비행기 크기](https://user-images.githubusercontent.com/22339132/57424040-3cd4b080-7251-11e9-8c30-87da193c0db0.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by BS00000001** [comment]
방향은 ref#653에서 해결하였습니다.
기체 하나만 크게 나온다는 것이 무슨 뜻인가요??

**Comment by sejin1031** [comment]
스크린샷 첨부했습니다.

**Comment by BS00000001** [comment]
아무래도 이 이슈 다시 오픈해야할 것 같습니다. 환경에 따라서 다르게 위치되는 것 같네요??

**Comment by BS00000001** [comment]
혹시 해결한 이후 화면 스크린샷 첨부해주실 수 있나요??

**Comment by sejin1031** [comment]
![수정후](https://user-images.githubusercontent.com/22339132/57424232-fdf32a80-7251-11e9-9a6d-7ea36bcd2cd1.png)

**Comment by sejin1031** [comment]
실행 환경은 크롬입니다.

**Comment by BS00000001** [comment]
기체 사이즈가 달랐네요 다시 닫겠습니다.
