### ISSUE TITLE
[FEATURE] 타이틀화면에서 GRADIUS 이미지 수정요청

### ISSUE THREAD

**Issue by doublik** [inureyes/gradios#671]
![image](https://user-images.githubusercontent.com/39623729/57433261-fee88400-7272-11e9-960a-095264e13981.png)
저희 게임이름은 GRADIOS이므로 위 이미지는 적절하지 않은 것같습니다.

**Comment by dudejrs** [comment]
제가 하겠습니다

**Comment by dury008** [comment]
저도 해보겠습니다

**Comment by dury008** [comment]
> 제가 하겠습니다

제가올린 로고라 바로 수정할수있어서 수정하였습니다
