### ISSUE TITLE
[BUG] ending 에서 랭킹테이블 뒤에 버튼이 눌리는 버그

### ISSUE THREAD

**Issue by doublik** [inureyes/gradios#684]
![image](https://user-images.githubusercontent.com/39623729/57448087-81813b80-7293-11e9-8311-b51ab7b1aefc.png)

랭킹테이블이 보일땐 뒤에있는 버튼이 눌리면 안됩니다.

**Comment by tutu772** [comment]
제가 해결해보겠습니다!
