### ISSUE TITLE
[FEATURE] 랭킹을 초기화 할 수 있게 해주세요.

### ISSUE THREAD

**Issue by doublik** [inureyes/gradios#686]
주기적으로 랭킹초기화가 필요할 것 같습니다.
@pbt98

**Comment by pbt98** [comment]
개발용일때만 만들어둬야할 것 같으니 키보드를 눌렀을때 되도록 구현하겠습니다.

**Comment by pbt98** [comment]
게임이 끝나고 하단에 하트 버튼으로 만들어두었습니다.
