### ISSUE TITLE
[FEATURE] 랭킹 테이블에서 X버튼

### ISSUE THREAD

**Issue by doublik** [inureyes/gradios#688]
![image](https://user-images.githubusercontent.com/39623729/57460073-69b7b080-72af-11e9-9f7c-c2b09d2add6e.png)

X버튼위에 마우스를 올렸을떄, 다른버튼위에 올렸을 때처럼 커서의 모양양이 pointer 로 변경되면 좋겠습니다.
![image](https://user-images.githubusercontent.com/39623729/57460204-a683a780-72af-11e9-8496-00c97c1ed132.png)
이와같은 모양이 나올 수 있게
(css의 cursor: pointer; 같은)

**Comment by tutu772** [comment]
제가 해결해보겠습니다!
