### ISSUE TITLE
[BUG] 게임이 끝난 후 랭킹 화면이 바로 나오지 않고 이상한 검은 창이 나옵니다.

### ISSUE THREAD

**Issue by jaehyeon99** [inureyes/gradios#695]
게임이 끝난 후 랭킹 화면이 바로 나오지 않고 검은 창이 나옵니다.
<img width="907" alt="스크린샷 2019-05-10 오전 11 40 40" src="https://user-images.githubusercontent.com/43145059/57499027-1aa66580-7319-11e9-906a-a5642b647c80.png">

**Comment by tutu772** [comment]
제가 해결하겠습니다!
