### ISSUE TITLE
[FEATURE] esc를 누르면 게임이 멈추고 설정 창이 나오는데 다시 esc를 누르면 게임이 시작되었으면 좋겠습니다.

### ISSUE THREAD

**Issue by jaehyeon99** [inureyes/gradios#696]
esc를 누르면 게임이 멈추고 설정이 나오고 게임을 다시 시작하기 위해서는 resume를 눌러야 하지만 esc를 눌렀을 때 다시 게임이 시작될 수 있는 기능을 추가하면 좋겠습니다.

**Comment by doublik** [comment]
제가 해보겠습니다.
