### ISSUE TITLE
[BUG] 아이템 이미지가 인식이 안됩니다

### ISSUE THREAD

**Issue by moris0712** [inureyes/gradios#699]
**Screenshots**
<img width="509" alt="스크린샷 2019-05-10 오후 1 35 19" src="https://user-images.githubusercontent.com/22339727/57502840-91972a80-7328-11e9-9fca-13c37854f734.png">

**Comment by siroch** [comment]
#678 #651 
mixing roguelite에서 merge시킨 내용으로 아직 이미지가 존재하지 않아서 생기는 현상이며 이미 올라와 있는 이슈입니다

**Comment by siroch** [comment]
버그가 아닌 기능 추가로 해야할거같고 이미 올라와있는 이슈이므로 close하겠습니다.
