### ISSUE TITLE
[BUG] 게임 끝난 후 랭킹보드의 점수가 이상합니다.

### ISSUE THREAD

**Issue by hhhhhhhhandongyeon** [inureyes/gradios#702]
![스크린샷 2019-05-10 오후 2 08 49](https://user-images.githubusercontent.com/43191614/57503903-40d60080-732d-11e9-87f4-9cc9f657424c.png)
수정해 주세요

**Comment by pbt98** [comment]
http://tallbin98.dothome.co.kr?Name="player"&Score=2834934589 이런식으로 브라우저에서 실행하면 데이터베이스에 Name 과 Score가 그대로 저장이 됩니다. 현재 상태에선 데이터를 쓸때마다 상위 10개를 제외하고 나머지 데이터는 모두 삭제하는 방식으로 구현했는데 브라우저에서 저 주소로 일부러 랭킹 정보를 보내지 않는 이상 이렇게 표시될 일은 없습니다. 추후 랭킹 초기화 버튼 추가 #686 로 해결할 예정입니다.
