### ISSUE TITLE
[BUG] 업그레이드 적용으로 일어나는 버그들 제보

### ISSUE THREAD

**Issue by siroch** [inureyes/gradios#703]
![image](https://user-images.githubusercontent.com/39474054/57504020-b4780d80-732d-11e9-825d-df90c04c9c0b.png)

![image](https://user-images.githubusercontent.com/39474054/57504029-bf32a280-732d-11e9-99c8-c7e98af0688d.png)

![image](https://user-images.githubusercontent.com/39474054/57504035-c6f24700-732d-11e9-84ab-1263efc56c67.png)

![image](https://user-images.githubusercontent.com/39474054/57504039-ceb1eb80-732d-11e9-9571-d86d23e19f6a.png)

위 사진들과 같이 총알이 중간에 비게 나오거나 속도가 너무 빨라져 더이상 연사로 나가지 않고 끊겨 나가는 현상이 일어나게 됩니다. 속도와 총알 갯수의 제한을 걸어서 해결하는것이 나을것같습니다.

**Comment by BS00000001** [comment]
ㅈㅔ가 해결하겠습니다.

**Comment by wogns3623** [comment]
아이템의 밸런스 조정은 기존 상수의 합연산으로 값을 조정하는 방식에서 곱연산으로 값을 조정하는 방식으로 바꾸면 될 것 같습니다. 또한 현재의 아이템들보다는 더욱 각 아이템들만의 개성이 드러나는 아이템들로 교체하고, 아이템을 스테이지가 끝날때마다 드롭하는 방식에서 다른 방식으로 바꾸어야 할 필요성도 있는 것 같습니다.

**Comment by wogns3623** [comment]
아이템의 값 조정을 곱연산 방식으로 하여 아이템을 여러개 먹더라도 공격속도가 0이 되는 일이 없도록 하였습니다.
