### ISSUE TITLE
[FEATURE]플레이어 개체와 적개체의 이동속도가 맞지 않습니다.

### ISSUE THREAD

**Issue by cvivis** [inureyes/gradios#704]
플레이어 개체의 이동속도에 비해 적개체의 이동속도가 비정상적으로 아이템의 확률 또한 낮기 때문에 빨라 게임의 밸런스가 맞지 않는것 같습니다.플레이어 개체 혹은 적개체의 이동속도를 다시 조정하거나 화살표 연속해서 눌러 대쉬기능을 아예 새롭게 만들어 게임의 기능을 추가하던지에 대한 개선이 필요한것같습니다!

**Comment by wogns3623** [comment]
대쉬기능은 이후 active item기능이 추가되었을때 추가하려고 한 기능입니다. 현재의 적 기체의 이동 매커니즘에 문제가 많은것은 사실이므로 조만간 패치가 이루어져야 할 것 같습니다.

**Comment by jaehyeon99** [comment]
#784 과 비슷한 문제로 적개체의 이동속도를 조정하였습니다.
