### ISSUE TITLE
[FEATURE] 스테이지별로 난이도 조절이 필요할거같습니다. 아니면 기체별로 스펙이 제한되어야 할 것 같습니다.

### ISSUE THREAD

**Issue by siroch** [inureyes/gradios#705]
![image](https://user-images.githubusercontent.com/39474054/57510836-ac769880-7342-11e9-9752-fb652e8bfdc1.png)

일정 수준이 되면 게임을 하는게 아닌 space bar만 누르고 있는것만으로도 게임이 진행되는 수준이 되어버립니다. 총알 갯수 제한도 걸어야 하며 난이도도 조절을 해야 할 것 같습니다.

**Comment by wogns3623** [comment]
아이템의 드랍 방식을 수정해야 하는 문제이므로 일단은 밸런스에 크게 영향을 미치는 addBullet 아이템과 fireRateUp 아이템의 희귀도를 조정하는 방식으로 수정하여야 할 것 같습니다.

아마 이후에 아이템이 충분히 많이 추가된다면 대부분의 아이템은 중복되어 나오지 않도록 바뀔 것이기 때문에 아이템이 더 추가되지 않는 이상은 지금은 임시로 드랍 확률을 조정하는 방법밖에는 없다고 생각합니다

**Comment by wogns3623** [comment]
문제가 되었던 아이템들의 희귀도를 조정하였습니다.
