### ISSUE TITLE
[BUG] 스테이지와 적 처치수가 숫자가 커질수록 겹치거나 잘려서 보이게 됩니다.

### ISSUE THREAD

**Issue by siroch** [inureyes/gradios#706]
![image](https://user-images.githubusercontent.com/39474054/57511472-5acf0d80-7344-11e9-943a-8756a06f7c80.png)

위 사진과 같이 나옵니다. 기능수정과 분리해야 할 것 같아서 따로 올립니다.

**Comment by wogns3623** [comment]
현재의 표기 방식은 후에 게임이 완성 단계에 근접했을 때 UI를 필연적으로 수정해야 하므로 지금은 중요도가 조금 떨어지는 문제라고 생각됩니다.

**Comment by siroch** [comment]
CodeOnWeb에서의 개발 진행기간이 얼마 남지 않아서 지금 수정해도 괜찮을 사항으로 보입니다.

**Comment by duncan2121** [comment]
제가 해결하도록 해보겠습니다
