### ISSUE TITLE
[FEATURE]control에서 조작방법에 대한 설명이 있는 창

### ISSUE THREAD

**Issue by aeuna** [inureyes/gradios#707]
조작방법과 게임에 대한 아이템 설명하는 창이 게임창에 제대로 맞지 않은데 게임화면에 풀화면이었으면 좋겠습니다.

![화면](https://user-images.githubusercontent.com/42725903/57511588-94a01400-7344-11e9-99e2-20d9698844ca.PNG)

**Comment by cvivis** [comment]
제가 하겠습니다
