### ISSUE TITLE
[FEATURE] 일정 시간이 지나면 생성된 아이템이 사라지면 좋겠습니다

### ISSUE THREAD

**Issue by AnOldStory** [inureyes/gradios#710]
일정 시간이 지나면 생성된 아이템이 사라지면 좋겠습니다

아이템을 먹지 않고 오랫동안 피하면 아이템이 화면에 쌓이는 거보다

1분정도 먹지 않으면 아이템이 사라져 빨리 먹어야한다는 긴장감을 유도하면 좋겠습니다

**Comment by wogns3623** [comment]
현재도 아이템을 10초 이상 방치하면 더이상 화면 경계에서 튕겨나지 않고 밖으로 사라집니다.
