### ISSUE TITLE
[FEATURE] 메인 화면에서도 랭킹 시스템을 볼 수 있는 기능이 있으면 합니다.

### ISSUE THREAD

**Issue by jiho5993** [inureyes/gradios#711]
현재는 게임이 끝날때만 랭킹 시스템을 확인할 수 있지만, 꼭 게임이 끝나야 볼 수 있다는 불편함을 줄이기 위해 아래와 같이 메인화면에도 랭킹을 보여주는 창을 띄울수 있게 구현하면 좋을 것 같습니다.
![스크린샷 2019-05-10 오후 5 28 12](https://user-images.githubusercontent.com/42717320/57513367-067a5c80-7349-11e9-87b8-cf41aee06ab9.png)

**Comment by doublik** [comment]
제가 해보겠습니다.

**Comment by doublik** [comment]
임시로 메인화면에서 ESC키를 눌러 랭킹창을 볼 수 있도록 만들었습니다.
