### ISSUE TITLE
[BUG] 타이틀화면에서 Control 버튼을 눌렀을때

### ISSUE THREAD

**Issue by doublik** [inureyes/gradios#716]
![image](https://user-images.githubusercontent.com/39623729/57569657-238b5a00-7433-11e9-8ada-324283614145.png)

이화면에서 뒤에있는 Start버튼과 EXIT버튼이 위치해있는곳을 클릭하면 이벤트가 발생합니다.
뒤에있는 버튼들이 클릭되지 않으면 좋겠습니다.

**Comment by tutu772** [comment]
제가 해결해보겠습니다!
