### ISSUE TITLE
[FEATURE] Stage에 따른 배경 변경

### ISSUE THREAD

**Issue by duncan2121** [inureyes/gradios#720]
**어떤 해결책을 선호하는지 설명해주세요**
제가 배경 이미지 5개를 new_design/background 위치에 추가하였습니다.
Stage가 넘어가면, 그 Stage의 배경을 제외한 다른 배경을 랜덤하게 나오도록 해주세요.

**Comment by tutu772** [comment]
제가 해결해보겠습니다!
