### ISSUE TITLE
[FEATURE] 설정 변경에 대한 색깔 변화

### ISSUE THREAD

**Issue by my9544** [inureyes/gradios#728]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
설정을 보면 on/off 키가 있는데 눌렀을때 색깔이 변하도록 해주세요.
아래 올린 사진과 같이요

**어떤 해결책을 선호하는지 설명해주세요**
색상 코드 변경

**고려했던 대안들에 대해 설명해주세요**
이미 고려해 보았던 다른 대안들에 대해 명확하고 간결하게 설명해주세요.

**추가적인 컨텍스트**
![색상변화](https://user-images.githubusercontent.com/22341351/57580842-bd154300-74e9-11e9-83d1-4bd873372aee.PNG)

**Comment by my9544** [comment]
대충 그려서 죄송합니다

**Comment by BS00000001** [comment]
제가 해결하겠습니다.
