### ISSUE TITLE
[FEATURE] 적의 움직임 개선 요청

### ISSUE THREAD

**Issue by rlagkdud** [inureyes/gradios#731]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
적의 움직임이 너무 갑작스러운 것 같습니다.

**어떤 해결책을 선호하는지 설명해주세요**
적이 보다 부드럽게 움직이면 게임이 더 재밌을것 같습니다.

**Comment by KImMyoungSoo** [comment]
제가 해보겠습니다

**Comment by jaehyeon99** [comment]
#784 번과 비슷하여 제가 수정하였습니다.

**Comment by wogns3623** [comment]
해당 풀 리퀘스트에서의 변경사항이 없어 assignees에서 제외시켰습니다
