### ISSUE TITLE
슈퍼아머 아이템의 기능에 대해 질문이 있습니다

### ISSUE THREAD

**Issue by wogns3623** [inureyes/gradios#732]
현재 슈퍼아머 아이템을 먹으면 5초동안 무적이 되어 적이나 적 총알과 충돌판정이 일어나지 않는데, 의도된 내용인가요? 아니라면 수정 부탁드립니다.

**Comment by BS00000001** [comment]
원래 의도는 충돌하면 적 총알과 적이 죽습니다.
제가 수정하겠습니다.

**Comment by BS00000001** [comment]
원래 의도와 맞게 수정하였고 필요없는 폴더를 지웠습니다.
