### ISSUE TITLE
[BUG] 5월 12일 23:44 기준 적에게 피격당해도 목숨이 줄지 않습니다.

### ISSUE THREAD

**Issue by sejin1031** [inureyes/gradios#735]
- 현재 최신버전으로 새로 clone 해와서 플레이 해보았는데, 적에게 피격을 당해도 생명은 줄지 않고, 적은 죽지만 kill 수가 늘지 않습니다. 

- 피격당할 때 생명이 줄도록 수정해야할거같습니다.

**Comment by AnOldStory** [comment]
제가해결하겠습니다
