### ISSUE TITLE
[FEATURE] Stage 에 따른 BGM 변경

### ISSUE THREAD

**Issue by duncan2121** [inureyes/gradios#745]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
제가 gradius1, 2, 3 음원을 audio에 추가했습니다. 스테이지 별로 다른 음악이 나오게 해주세요.
**어떤 해결책을 선호하는지 설명해주세요**
stage 가 변경되면 bgm 이 그 전 stage 에 나왔던 음악을 제외하고 랜덤으로 나오게 해주세요

**Comment by tutu772** [comment]
제가 해결해보겠습니다!
