### ISSUE TITLE
[BUG] ranking 표기에 문제가 있습니다.

### ISSUE THREAD

**Issue by Darkcruel** [inureyes/gradios#758]
**Describe the bug**
동일한 점수를 얻어 ranking 에 올라갈때 화살표가 2개 이상으로 늘어납니다.

**Expected behavior**
동일한 점수를 얻어도 ranking 창에 화살표가 하나만 있었으면 좋겠습니다.

**Screenshots**
<img width="960" alt="Show_Ranking_Bug" src="https://user-images.githubusercontent.com/22339403/57662810-2c934b80-762c-11e9-9c2c-a474e351134e.png">

**Comment by duncan2121** [comment]
제가 해결하겠습니다
