### ISSUE TITLE
[BUG] electron을 이용할때 포트를 초기화하기

### ISSUE THREAD

**Issue by 3people** [inureyes/gradios#766]
**Describe the bug**
 변경사항을 반영해도 현재 코드에 9900포트가 활성화 되있으면 반영이 안됩니다.
**To Reproduce**
포트를 실행할때마다 재생성해야할듯합니다
**Expected behavior**
 수정을 하여도 9900 포트가 켜져있기때문에 직접 포트를 수정해야함

**Screenshots**
![Screenshots](https://raw.githubusercontent.com/3people/test-reposit/master/%E1%84%89%E1%85%B3%E1%84%8F%E1%85%B3%E1%84%85%E1%85%B5%E1%86%AB%E1%84%89%E1%85%A3%E1%86%BA%202019-05-14%20%E1%84%8B%E1%85%A9%E1%84%92%E1%85%AE%202.29.02.png)

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser []
 - Version []

**Additional context**

**Comment by AnOldStory** [comment]
어떤 명령어로 실행하였을떄 나오는 오류인지 조금 더 자세히 알려주실수있으신가요
