### ISSUE TITLE
[FEATURE] 라이프 이미지가 직관적이지 않습니다. 

### ISSUE THREAD

**Issue by KMJAE** [inureyes/gradios#772]
라이프르 표시하는 "HEALTH" 바로 옆에 " : " 이 표시가 있고 그 옆에 라이프 이미지가 삽입돼있지 않습니다. 또한 라이프 이미지가 직관적이지 않다고 판단, 빨간 하트 이미지로 대체했음 좋겠습니다.

**Comment by cgm-seungho** [comment]
제가 해결해보겠습니다.
