### ISSUE TITLE
[FEATURE] electron사용에 따른 readme or wiki 수정

### ISSUE THREAD

**Issue by 3people** [inureyes/gradios#774]
**어떤 해결책을 선호하는지 설명해주세요**
 * electron, electron packager 설치 방법 readme나 wiki에 추가하기

**추가적인 컨텍스트**
 * 기존에 wiki에 있는 gulp 사용은 지워도 되는것인지? gulp 추가하신 분이 수정해주셨으면 합니다! @AnOldStory

**Comment by AnOldStory** [comment]
gulp는 gulp만의 사용법이 필요하여 다른 사용법을 위주로 추후에 명령어를 바꿀 예정입니다

**Comment by 3people** [comment]
> gulp는 gulp만의 사용법이 필요하여 다른 사용법을 위주로 추후에 명령어를 바꿀 예정입니다
> => 아직은 지우지 않았으면 좋겠습니다.

**Comment by waristo** [comment]
#805 와 연계해서 제가 작성하겠습니다
