### ISSUE TITLE
[BUG] 아이템 이미지 수정 요청

### ISSUE THREAD

**Issue by kimDDong** [inureyes/gradios#775]
**Describe the bug**
아이템 이미지가 깨집니다.

**To Reproduce**
게임 실행 후 2레벨 적을 잡았을 때 나오는 첫 아이템의 이미지가 깨져서 나옵니다.
![스크린샷(14)](https://user-images.githubusercontent.com/22341308/57681342-76028b80-766a-11e9-961c-cf9c3eaf0277.png)

**Comment by jaehyeon99** [comment]
아이템 이미지가 깨지는 것이 아니라 원래 저 이미지 아닌가요?

**Comment by wogns3623** [comment]
현재 fireRateUp 아이템에 해당하는 이미지가 없는 상태여서 그렇습니다.

**Comment by kimDDong** [comment]
그렇군요! 감사합니다~
