### ISSUE TITLE
[FEATURE] BGM OFF인 상태에서 볼륨 증가

### ISSUE THREAD

**Issue by kimDDong** [inureyes/gradios#778]
BGM OFF인 상태에서 볼륨을 높였을 때 BGM ON으로 바뀌게 해주세요.

현재
![스크린샷(16)](https://user-images.githubusercontent.com/22341308/57681955-b7e00180-766b-11e9-9ef4-63bba27b66f4.png)
![스크린샷(17)](https://user-images.githubusercontent.com/22341308/57681956-b7e00180-766b-11e9-967d-48b44af5bc2a.png)
![스크린샷(18)](https://user-images.githubusercontent.com/22341308/57681959-b7e00180-766b-11e9-956c-bbfbc3cc2729.png)
**SFX Volume이 40 이지만 Music은 여전히 OFF입니다! (실제 게임 내 음향은 나옵니다!)

**Comment by jaehyeon99** [comment]
제가 해결해보겠습니다.

**Comment by jaehyeon99** [comment]
일단 BGM 버튼이 OFF 인 상태에서 증가하였을 때 바뀌는 것은 게임 내와 설정 창 모두에서 수정하였지만 
ON 인 상태에서 OFF로 변경 될 때 bgm volume 과 sfx volume 모두 0일 때 OFF 로 변경되어야 하지만 둘 중 하나만 0이 되어도 OFF로 바뀌게 되는 현상이 일어납니다. 수정 부탁드립니다.
