### ISSUE TITLE
[FEATURE] 적이 죽을때 소리가 너무 시끄럽습니다

### ISSUE THREAD

**Issue by hhhhhhhhandongyeon** [inureyes/gradios#782]
너무 지지직거려서 귀에 거슬립니다. 없애거나 다른소리로 전환했으면 좋겠습니다.

**Comment by jaehyeon99** [comment]
제가 해결하겠습니다
피격시 이미지가 있으므로 굳이 소리가 없어도 됨으로 판단, 소리를 없애도록 하겠습니다.

**Comment by wogns3623** [comment]
게임에 사운드이펙트가 없으면 게임을 할 때 허전할 것 같습니다. 차라리 소리 크키를 줄이는 방향으로 가는것이 좋을 것 같습니다.

**Comment by jaehyeon99** [comment]
소리를 최대한 줄여도 지지직 소리가 거슬린다는 의견이 많아서 일단은 없애도록 하겠습니다.
추후에 다른 소리를 찾아 올리도록 하겠습니다.
