### ISSUE TITLE
[FEATURE]비행기 이미지를 선택하는 기능을 추가했으면 좋겠습니다

### ISSUE THREAD

**Issue by sujeong1217** [inureyes/gradios#791]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
비행기 이미지를 선택하는 기능을 추가했으면 좋겠습니다

**어떤 해결책을 선호하는지 설명해주세요**
start버튼을 클릭한 후 비행기 선택 페이지로 넘어가 원하는 비행기(우주선)을 선택하는 방법 등.

**추가적인 컨텍스트**
![image](https://user-images.githubusercontent.com/43164999/57706772-59ce1100-76a1-11e9-8168-56187817c4e7.png)

추가적인 비행기 이미지 파일은 newship264x64x5.png 로 이미지 파일에 추가하겠습니다.

**Comment by moris0712** [comment]
스프리트 사진이 분할이 되질 않는것같습니다.

<img width="912" alt="스크린샷 2019-05-17 오전 4 03 03" src="https://user-images.githubusercontent.com/22339727/57880623-2aaecf80-785a-11e9-8879-d9af2ff00d35.png">
