### ISSUE TITLE
[BUG] 게임이 끝난 후에 랭킹창 닫으니 버튼들이 사라졌습니다.

### ISSUE THREAD

**Issue by hhhhhhhhandongyeon** [inureyes/gradios#794]
![스크린샷 2019-05-15 오전 12 27 46](https://user-images.githubusercontent.com/43191614/57710698-64d86f80-76a8-11e9-8c3a-8d53c1d54362.png)

**Comment by jaehyeon99** [comment]
제가 해보니 제대로 실행되는데 자세한 버그좀 말씀해주시면 감사하겠습니다.
