### ISSUE TITLE
[FEATURE] Electron 앱 실행파일 만들기

### ISSUE THREAD

**Issue by waristo** [inureyes/gradios#805]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
일렉트론 앱을 바로 실행할수있는 실행 파일 만들기

**어떤 해결책을 선호하는지 설명해주세요**

**고려했던 대안들에 대해 설명해주세요**

**추가적인 컨텍스트**

**Comment by waristo** [comment]
제가 해요

**Comment by AnOldStory** [comment]
이미 구현되어있습니다. npm test를 실행시키면 즉시 실행이 가능합니다.

**Comment by waristo** [comment]
실행파일을 만들어주는 코드 삽입.
리눅스/ 맥/ 윈도우 버전 만들었으나 용량 문제로 파일에는 윈도우 버전만 올림.
https://github.com/inureyes/gradios/releases/tag/v1.0.0
릴리즈 추가 하였고, 스스로 실행파일을 만들수 있는 설명 md파일 다음에 추가 하겠습니다.
