### ISSUE TITLE
[BUG] 게임 룰과 다른 실제 플레이

### ISSUE THREAD

**Issue by kimDDong** [inureyes/gradios#813]
게임 룰에서는 최대 총알 갯수가 6개입니다.
![help](https://user-images.githubusercontent.com/22341308/57777957-0968b900-775e-11e9-95e4-16d4c37a23b3.jpg)

하지만 실제 플레이에서는 제한 없이 증가하는 것으로 보여집니다.
![스크린샷(20)](https://user-images.githubusercontent.com/22341308/57777898-e50cdc80-775d-11e9-8e08-ecda485dab68.png)

이로 인해 #812 버그 현상도 일어나는 것 같습니다.

총알 갯수 제한을 비롯한 여러가지 게임 룰을 지킬 수 있도록 수정해주시기 바랍니다.

**Comment by moris0712** [comment]
다시 말씀드리지만 저 설명은 코드 분할전 내용이며 코드 분할후 설명 업데이트가되지않았습니다.
코드분할이후 많은 코드가 변경되는등 없어지는경우 등 저 설명서는 현재 버전과 다릅니다.

**Comment by kimDDong** [comment]
아하! 공지해주시면 감사하겠습니다~
