### ISSUE TITLE
[BUG] 메인 메뉴에서 CREDIT을 연타 시 버그

### ISSUE THREAD

**Issue by kimDDong** [inureyes/gradios#814]
![image](https://user-images.githubusercontent.com/22341308/57778365-de329980-775e-11e9-9561-6df4777b7404.png)
메인 메뉴에서 CREDIT 버튼이 있는 부분을 연타하면
![image](https://user-images.githubusercontent.com/22341308/57778405-f1de0000-775e-11e9-9573-05ed26c26795.png)
그 횟수 만큼 CREDIT 화면에서 back 버튼을 연타해야 메인 화면으로 돌아가집니다.

CREDIT화면에서 back 버튼을 한번만 클릭해도 메인 화면으로 돌아갈수 있게 해주세요.

**Comment by moris0712** [comment]
제가 해결하겠습니다
