### ISSUE TITLE
[BUG] #815와 연계 된 버그

### ISSUE THREAD

**Issue by kimDDong** [inureyes/gradios#816]
#815 의 상황처럼 세팅을 한 뒤 CREDIT 화면에서 back 버튼을 누릅니다.

![image](https://user-images.githubusercontent.com/22341308/57778973-2ef6c200-7760-11e9-9bfd-65be9f6e1f88.png)
다시 CONTROL 화면으로 돌아와집니다.

여기서 메인 화면의 START와 EXIT 버튼이 있던 위치를 클릭합니다.
첫번째의 경우 게임이 실행 되고, 두번째의 경우 게임이 종료됩니다.

/**
 * 메인 화면에서 CONTROL 버튼을 눌러 들어온 직후에는 해당 버그가 발생하지 않습니다.
 * #815 의 상황 이후에 버그가 발생합니다. 
 * 여러 화면을 이동하면서 각 화면이 실행되는 코드를 종료시키지 않아 생긴 버그로 추정됩니다.
 */

**Comment by moris0712** [comment]
#815와 같이 해결하였습니다.
