### ISSUE TITLE
[FEATURE] 게임 아이템 이미지 및 효과

### ISSUE THREAD

**Issue by kimDDong** [inureyes/gradios#818]
![help](https://user-images.githubusercontent.com/22341308/57779530-34a0d780-7761-11e9-878b-8a4e00d3af2c.jpg)
게임 룰에 적혀 있는 아이템들과 실제 플레이에 나오는 아이템들의 이미지 및 효과들이 달라서 게임하는데 혼돈을 줍니다.
예를 들어 기체 발사 총알 수의 증가는 ![power_up](https://user-images.githubusercontent.com/22341308/57780180-b5140800-7762-11e9-94a8-418ec964eb77.png) 이지만 실제 플레이 중에는 ![addBullet](https://user-images.githubusercontent.com/22341308/57780228-c9f09b80-7762-11e9-9684-58b0ac972b95.PNG) 이 아이템을 먹었을 때 총알 수가 증가 하더라구요.

![addPenetration](https://user-images.githubusercontent.com/22341308/57780281-e2f94c80-7762-11e9-9f9e-412f06fe0f2b.PNG) 이 아이템도 설명이 없어 무슨 효과를 주는지 알수가 없네요!

* 점수 뻥튀기 아이템들은 나오긴 하나요?! 한번도 나와본적이 없어서요. 만약 그렇지 않다면, 이 아이템들도 구현해주세요!

**Comment by kimDDong** [comment]
새로운 설명서를 업데이트 해주셨으면 합니다!

**Comment by jaehyeon99** [comment]
이슈 #622 번과 유사한 문제로 해결하였습니다. 
추가할 사항이 있다면 말씀해주세요
