### ISSUE TITLE
[FEATURE] 메인 메뉴에서 게임 종료 시 확인 질문

### ISSUE THREAD

**Issue by kimDDong** [inureyes/gradios#838]
![image](https://user-images.githubusercontent.com/22341308/57860221-7435f500-782f-11e9-9dda-500179f5750d.png)
여기서 MAIN MENU를 클릭하면 
![image](https://user-images.githubusercontent.com/22341308/57860211-6c765080-782f-11e9-9a96-665343796ee7.png)
이런 메세지박스가 등장하는데
메인 메뉴에서도 EXIT 버튼을 눌렀을 때 한번 더 확인하는 기능을 추가했으면 좋겠습니다.
ex) Do you really want to close the running game? (Y / N)

**Comment by waristo** [comment]
I'll do this
