### ISSUE TITLE
[FEATURE] 게임 종료 버튼 추가

### ISSUE THREAD

**Issue by kimDDong** [inureyes/gradios#839]
메인 메뉴에 게임 종료 버튼(EXIT)이 있는데
![image](https://user-images.githubusercontent.com/22341308/57860674-39808c80-7830-11e9-9ef7-2a1602c59f52.png)
게임 플레이 중이나
![image](https://user-images.githubusercontent.com/22341308/57860573-0d650b80-7830-11e9-8417-37a8fb97086b.png)
게임 종료 후에도 종료 버튼이 있으면 좋겠습니다.

**Comment by waristo** [comment]
I'll do this '-^

**Comment by waristo** [comment]
게임 플레이 중, 설정화면
게임 종료 후.
창 종료 버튼 생성했습니다.
