### ISSUE TITLE
[FEATURE] 비행기 선택 다시 추가하였습니다.

### ISSUE THREAD

**Issue by moris0712** [inureyes/gradios#842]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
비행기 선택을 추가하였습니다
그외에도 스프리트 비행기 사진이 추가되면 그것도 추가하도록하겠습니다.

**Comment by kimDDong** [comment]
armerShip64x64x5_ori.png 파일을 이용해서 추가하면 어떨까요?!
