### ISSUE TITLE
[FEATURE] 필요없는 이미지나 파일들을 삭제 했으면 좋겠습니다.

### ISSUE THREAD

**Issue by jaehyeon99** [inureyes/gradios#846]
gradios 파일에 보면 필요없는 이미지나 오디오 파일들, 코드들이 많이 남아있습니다.
필요없는 것들을 다 삭제해주었으면 좋겠습니다.

**Comment by kimDDong** [comment]
추가적인 업데이트를 위한 파일들도 남아 있으므로 메인컨테이너만이 삭제 권한을 갖게 하는 것이 어떨까요??
