### ISSUE TITLE
[FEATURE] 컨트롤 설명 창에서 뒤로가기(back) 버튼이 설명과 겹칩니다.

### ISSUE THREAD

**Issue by Anyohan** [inureyes/gradios#849]
<img width="889" alt="KakaoTalk_Photo_2019-05-17-11-50-27" src="https://user-images.githubusercontent.com/43191514/57899995-24d8de80-789a-11e9-9488-c648b1ed4818.png">
컨트롤 설명 창에서 뒤로가기(back) 버튼이 설명과 겹칩니다.

**Comment by jaehyeon99** [comment]
제가 해결하겠습니다.
