### ISSUE TITLE
[FEATURE] 메인화면에 버전도 추가했으면 좋겠습니다.

### ISSUE THREAD

**Issue by wangjh789** [inureyes/gradios#852]
<img width="300" alt="스크린샷 2019-05-17 오후 3 49 31" src="https://user-images.githubusercontent.com/19744909/57908632-76459580-78bb-11e9-8dcb-34e8b52e1548.png">

gradious  중앙하단에 조그맣게 'ver.1.0.0' 과 같은 버전이 표기되어 있으면 좋겠습니다.

**Comment by cuppaamukkaacoffee** [comment]
제가 하겠습니다.

**Comment by 3people** [comment]
제가 하겠습니다
