### ISSUE TITLE
[FEATURE] 모든 종료버튼에 다시 묻는 창.

### ISSUE THREAD

**Issue by waristo** [inureyes/gradios#856]
**기능 추가 요청이 특정 문제와 관련이 있나요? 설명해주세요.**
현재 일부 종료버튼에만 다시 묻는 창이 뜨는데 모든 종료버튼에 개선.

**어떤 해결책을 선호하는지 설명해주세요**
현재 일부 종료버튼에만 다시 묻는 창이 뜨는데 모든 종료버튼에 개선.

**고려했던 대안들에 대해 설명해주세요**
이미 고려해 보았던 다른 대안들에 대해 명확하고 간결하게 설명해주세요.

**추가적인 컨텍스트**
이 기능 추가 요청과 관련된 상황이나 스크린샷들을 추가해주세요.

**Comment by kimDDong** [comment]
제가 하겠습니다~
