### ISSUE TITLE
[FEATURE] Health와 Alien 수 표시 간략하게 변경 요청

### ISSUE THREAD

**Issue by HochulHwang** [inureyes/gradios#863]
현재 상태 표시의 "Health:"와 "Alien:" 는 필요하지 않다고 생각합니다. 또한 수명 Heart의 위치가 애매해서 수정하였으면 좋겠습니다. 

<img width="496" alt="Screen Shot 2019-05-18 at 2 21 26 PM" src="https://user-images.githubusercontent.com/31910827/57965025-347b2480-7979-11e9-8dd3-f9f921843ebf.png">

**Comment by jaehyeon99** [comment]
alien은 다음스테이지로 넘어가기 위한 남은 적 수이기 때문에 필요하지 않을까요?

**Comment by jaehyeon99** [comment]
제가 해결해 보겠습니다.
