### ISSUE TITLE
[BUG] 현재 총알이 파괴되지 않는 버그가 발생하고 있습니다.

### ISSUE THREAD

**Issue by jaehyeon99** [inureyes/gradios#864]
현재 총알이 파괴되지 않는 버그가 발생하고 있으니 수정 부탁드립니다.

**Comment by kimDDong** [comment]
#861 과 동일한 버그인가요??

**Comment by jaehyeon99** [comment]
아뇨 저 당시에는 게임 시작시에는 정상적으로 총알이 파괴되었지만, 지금 현재에는 총알이 시작부터 파괴되지 않는 버그로보입니다.

**Comment by kimDDong** [comment]
전에 실행시킬때 pull 하지 않은게 아닐까요?
#861 이후 변경 사항으로는 해당 버그가 생길 일이 없는것 같습니다.

**Comment by jaehyeon99** [comment]
아 그렇네요
