### ISSUE TITLE
[BUG] 치트 모드 중에 아이템 습득

### ISSUE THREAD

**Issue by kimDDong** [inureyes/gradios#871]
치트 모드를 ON한 상태에서 아이템을 습득하였을 시 치트로 얻은 능력치가 초기화 되고, 치트모드가 풀리는 버그를 발견하였습니다.

**Comment by moris0712** [comment]
치트모드 on 후 off시키면 기본 능력치로 돌아오게끔 설정,
치트모드 on일시 c 공속증가 v 이동속도증가
+추가 d 공속감소 f 이동속도감소
