### ISSUE TITLE
[BUG] fireRateUp 아이템 아이콘 출력 오류

### ISSUE THREAD

**Issue by roasted-penguin** [inureyes/gradios#879]
**Describe the bug**
fireRateUp 아이템 아이콘이 깨져 나옴.

**To Reproduce**

**Expected behavior**
아이콘 출력되게 코드 수정 혹은 아이콘 추가 요청
**Screenshots**
![image](https://user-images.githubusercontent.com/43606521/57984419-9bdac680-7a96-11e9-9c61-2c971e6356d6.png)

**Additional context**

**Comment by yelimpark** [comment]
제가 하겠습니다.
