### ISSUE TITLE
[BUG] 치트 모드 해제 무적 버그

### ISSUE THREAD

**Issue by kimDDong** [inureyes/gradios#886]
치트 모드 ON 상태에서 무적 치트를 사용한 상태에서
치트 모드를 OFF 할 시에 아이템을 습득 하기 전까지는 무적이 유지되는 버그가 있습니다.

**Comment by ArcheSeraph** [comment]
치트 모드를 끌 때하는 초기화에 Player.info.isInvincible = false 를 추가하여 무적 기능을 끄도록 했습니다.
<img width="763" alt="스크린샷 2019-05-21 오전 8 13 37" src="https://user-images.githubusercontent.com/14332935/58057620-7e921f00-7ba0-11e9-97df-52a112e56b07.png">
