### ISSUE TITLE
[BUG] cheat mode ON 상태에서 아이템 습득

### ISSUE THREAD

**Issue by kimDDong** [inureyes/gradios#891]
cheat mode ON 상태에서 아이템 습득 시 해당 능력치가 적용되지 않습니다.

예를 들어, add_bullet 아이템을 먹더라도 총알 갯수가 늘어나지 않습니다.

**Comment by ArcheSeraph** [comment]
Cheat Mode 추가하신 분께서 치트 모드 상태에서는 아이템을 획득해도 적용되지 않게 하려고 하셨는지 첨부한 이미지와 같이 구현하셨습니다. 따라서 치트 모드 상태에서도 아이템 적용이 가능하도록 if 문을 제거했습니다.
<img width="569" alt="스크린샷 2019-05-21 오전 7 51 39" src="https://user-images.githubusercontent.com/14332935/58057281-43dbb700-7b9f-11e9-8df2-897b6e09de9b.png">

**Comment by moris0712** [comment]
맞습니다 설명 감사드립니다
