### ISSUE TITLE
[BUG] 처음 시작시 사운드가 나오지 않음

### ISSUE THREAD

**Issue by inureyes** [inureyes/gradios#98]
**Describe the bug**
처음 시작할 때 소리가 안 나옵니다. 한 번 죽어야 나옵니다.

**To Reproduce**
1. 실행합니다.
2. 소리가 안 나옵니다.

**Expected behavior**
처음 시작할 때 소리가 나와야 합니다.

**Comment by cuppaamukkaacoffee** [comment]
제가 하겠습니다.
