### ISSUE TITLE
[BUG] 게임 종료시 player's bullet 초기화 안됨

### ISSUE THREAD

**Issue by kimDDong** [inureyes/gradios#99]
**Describe the bug**
게임 승리 또는 패배 시 player의 bullet이 초기화가 안됨

**To Reproduce**
1. 게임 실행
 2-1. 게임 승리
   확인 : (player의 bullet이 남아있음) 
 2-2. 게임 패배
   확인 : (player의 bullet이 남아있음)    

**Expected behavior**
게임 종료 후 재실행 시에 player의 bullet으로 인한 다음 게임에 차질을 없앰.

**Comment by dudejrs** [comment]
제가 하겠습니다
